### ISSUE TITLE
Field with custom inputType (TYPE_CLASS_NUMBER only!)

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#10]
I really like the idea of having custom elements and it works great! Thanks. I want to have a `number()` input, but I don't want to allow any symbols (.,-), only numbers.

To achieve this I can create a custom element and set the inputType of the editText to:

```
editTextValue.inputType = InputType.TYPE_CLASS_NUMBER
```
inside my ViewBinder.

For this to work, I have to create 4 classes:

- FormBuilderExtensions -> to register my custom method
- OnlyNumbersElement 
- OnlyNumbersViewBinder
- OnlyNumbersViewState

The problem: analyzing all the code written to make it work, in the end I changed only one line:

The original FormNumberEditTextViewBinder:
```
editTextValue.setRawInputType(InputType.TYPE_CLASS_NUMBER or InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS)
```

My custom element:
```
editTextValue.inputType = InputType.TYPE_CLASS_NUMBER
```

I mean, could be a better way to specify a custom inputType or even better, a custom `setOnFocusChangeListener`? Or I don't know, a way so we can have access to the `editTextValue` inside our activity?

**Comment by TheJuki** [comment]
Yeah...maybe I can make that an option for FormNumberEditTextElement? I am sure I will be able to expose editTextValue to the activity layer.

**Comment by Fuhrmann** [comment]
An option would be nice. Would be even better if the editText is exposed, but if this isn't possible, that's ok.

**Comment by TheJuki** [comment]
I am currently working on exposing the views in the form element layouts to the models in a separate branch. For now, try out version 2.1.3 where the numbersOnly field has been added.

**Comment by Fuhrmann** [comment]
Great! Thanks for your work.

**Comment by Fuhrmann** [comment]
This is working as expected too! Just tested on 2.1.3 version.

**Comment by TheJuki** [comment]
Great! I am closing this issue.
