### ISSUE TITLE
Fragment inside Custom Form Field

### ISSUE THREAD

**Issue by alexodus** [TheJuki/KFormMaster#100]
I need to use a fragment (AutocompleteSupportFragment from Places SDK) inside a custom form field. Do you provide an example about it?

**Comment by TheJuki** [comment]
Sorry for the delay on this.

I have added an example. Please check out the docs: https://thejuki.github.io/KFormMaster/custom/placeAutocomplete/

**Comment by alexodus** [comment]
thank you!

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
