### ISSUE TITLE
set{Max/Min}Date on DatePicker  inside FormPickerDateElement

### ISSUE THREAD

**Issue by alexodus** [TheJuki/KFormMaster#101]
is desiderable to have the possibility to indicate min and max date inside FormPickerDateElement

**Comment by TheJuki** [comment]
I just released [6.3.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if minimumDate and maximumDate work for you.

**Comment by alexodus** [comment]
PERFECT!!!! Thanks

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
