### ISSUE TITLE
FormSegmentedElement: Enabled property not working

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#102]
## Description

When I set the "enabled" property of the FormSegmentedElement to false, the user can change the value further.

I expect, that the form element is disabled if enabled == false. On click/tab should nothing happen.

Example:
```
formBuilder = form(context!!, recyclerView!!) {
            segmented<String>(1) {
                options = listOf("test 1", "test 2")
                value = "test 1"
                enabled = false
            }
}
formBuilder.getFormElement<FormSegmentedElement<String>>(1).enabled = false
```

### KFormMaster version

* Version: 6.3.0

### System information

* Android OS: 8.1/Latest
* Issue in Emulator: Yes
* Issue in physical device: Yes

**Comment by TheJuki** [comment]
I just released [6.3.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if disabling the FormSegmentedElement works for you.

**Comment by darkwood-studios** [comment]
hm interesting. Is it the expected behavior that the value of a disabled field is NULL?

Because the field is not enabled for user does not mean that the field couldn't have a value, or what do you think?

**Comment by darkwood-studios** [comment]
... and another strange thing since the update:

I changed the color of the fields when they become disabled. this is the code

formBuilder.getFormElement<FormSegmentedElement<String>>(1).value = type
formBuilder.getFormElement<FormSegmentedElement<String>>(1).enabled = enabled

        if (!enabled) {
            val color = ResourcesCompat.getColor(resources, R.color.colorDisabled, null)
            formBuilder.getFormElement<FormSegmentedElement<String>>(FormField.METERTYPE).tintColor = color
        }

The color behind R.color.colorDisabled is #B2B2B2. With 6.3.0 it worked.

With the 6.3.2 the color results in #757575

Do you have an idea how this could happen?

**Comment by TheJuki** [comment]
I just released [6.3.3](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the Segmented Element value remains.

**Comment by darkwood-studios** [comment]
works great. thank you very much! :)

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
