### ISSUE TITLE
FormPickerDateElement: dateFormat not working

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#106]
Example:

            ```
date(FormField.BIRTHDAY) {
                title = "Birthday"
                dateValue = customer?.getBirthdayDate()
                dateFormat = SimpleDateFormat("dd.MM.yyyy", Locale.GERMAN)
            }
```

After selecting the date I got "1994-03-19 13:44:03" but I'm expecting "19.03.1994" as provided in dateFormat.

**Comment by TheJuki** [comment]
Is it displaying "1994-03-19 13:44:03" on the form? I cannot recreate this using `dateFormat = SimpleDateFormat("dd.MM.yyyy", Locale.GERMAN)`

**Comment by darkwood-studios** [comment]
Yes it's displayed "1994-03-19 13:44:03". Same problem for dateTime field. This is my code

```
formBuilder = form(context!!, recyclerView!!, this) {            
dateTime(1) {
                title = "Datetime..."
                dateValue = null
                dateFormat = SimpleDateFormat("dd.MM.yyyy HH:mm", Locale.GERMAN)
            }
}
```

After choosing date and time it results in "1994-03-19 13:44:03" (displayed in the input field), but it should be "19.03.1994 13:44"

I'm using 6.3.0 on a API 27 Pixel 2 XL Emulator.

**Comment by TheJuki** [comment]
I just released [6.3.3](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the date format works for you now. (Still cannot replicate)

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.

**Comment by darkwood-studios** [comment]
Same problem in 6.3.3...

just to make sure I provide you some screens.
![date_issue_2](https://user-images.githubusercontent.com/8148815/54530632-96bca680-4983-11e9-93d1-36b5cba1a06e.jpg)
![Uploading date_issue_1.jpg…]()

**Comment by mohamad-abuzaid** [comment]
I tried reproducing the issue but couldn't... Date formatting is working fine with me.

**Comment by darkwood-studios** [comment]
Ok, it seems like it's working fine now. Maybe there was a bad constellation of my english emulator and the german date formats. Within the final app it is working as expected.

I'm closing the issue so that you have one problem less to care.
