### ISSUE TITLE
"textView" should not use "colorFormMasterElementTextDisabled"

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#107]
In 6.3.2 I changed the "colorFormMasterElementTextDisabled" to change the color of disabled input field. But all of my textViews changed, too. I think this is a bug since a textView is not a disabled input. 

(even if I set enabled = true, the color looks like disabled)

**Comment by TheJuki** [comment]
textView is sorta disabled in that you cannot edit it. I can make it so it uses a different color from color.xml

**Comment by TheJuki** [comment]
I just released [6.3.3](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the color in colors.xml: colorFormMasterElementTextView works for you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.

**Comment by darkwood-studios** [comment]
Beautifull. Thank you. 👍
