### ISSUE TITLE
Inline FormPickerDateElement

### ISSUE THREAD

**Issue by soareseneves** [TheJuki/KFormMaster#117]
Hey there,

Thanks for this awesome library.

I was wondering if you could implement an Inline Date Picker Element that would look like this: https://github.com/xmartlabs/Eureka#date-rows it's the "Date Row (Inline)"

**Comment by TheJuki** [comment]
Do you know of an Android library that currently does that?

**Comment by soareseneves** [comment]
Not really sure, but it should work just like the header element “collapse/expand” feature but with a slightly slower animation, I will take a look at this after I finish the Image Element.

**Comment by soareseneves** [comment]
Hello again @TheJuki ! It has been a while, I've been busy with other projects but now I am back to business xD, if this has not been implemented yet I can help with that! I have already created a fully customized InlineDateElement and InlineDateTimeElement, should I create a pull request for you to test it out or just place the custom rows code here?

**Comment by TheJuki** [comment]
@soareseneves Go ahead with a pull request!

**Comment by soareseneves** [comment]
Done! #196
