### ISSUE TITLE
Java example for setValidityCheck?

### ISSUE THREAD

**Issue by jlayt** [TheJuki/KFormMaster#124]
## Description

Bit of a newb to calling Kotlin from Java. I'm trying to call setValidityCheck() from Java to set my own Java lamba, but it's not clear if/how I can access the element and its variables/methods to get, for example, the element value when I do so. Can you give an example, perhaps added to the main Java example code? Or is it not possible to access the element from inside a Java lambda?

### Expected behavior

To be able to access the Kotlin element and its variable/methods in the Java lambda.

### Actual behavior

I don't know if it's even possible?

### Steps to reproduce the bug

1. Know nothing about Kotlin
2. Try to call setValidityCheck() from Java
3. Much googling...

### KFormMaster version

* Version: Latest

### System information

* Android OS: Latest
* Issue in Emulator: Untested
* Issue in physical device: Untested

**Comment by TheJuki** [comment]
I just added this to the Java example:

```java
FormEmailEditTextElement email = new FormEmailEditTextElement(Tag.Email.ordinal());
        email.setTitle(getString(R.string.email));
        email.setHint(getString(R.string.email_hint));
        email.setValidityCheck(() -> {
            if (email.getValue() != null) {
                return android.util.Patterns.EMAIL_ADDRESS.matcher(email.getValue()).matches();
            } else {
                return false;
            }
        });
        elements.add(email);
```

Let me know if that works for you. Basically you just need to check the current element value and return a boolean.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
