### ISSUE TITLE
icon/imageview next the title

### ISSUE THREAD

**Issue by tianzhuqiao** [TheJuki/KFormMaster#129]
Thanks for the great project. Do we have any plan to support icon/imageview next to the title of each element (hide if not set)? Sometime an icon/image is more intuitive than text only.

**Comment by darkwood-studios** [comment]
Maybe with some optional click event for the icon? I'm planning to add some GPS-functionality to an icon next to the title of a zip field. If the kForm could provide a click listener for this icon the things would become much easier.

**Comment by TheJuki** [comment]
I just released [6.4.8](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new properties: titleIcon, titleIconLocation, titleIconPadding, and onTitleIconClick work for you. titleIcon expects a drawable: https://thejuki.github.io/KFormMaster/element/base/#title-icon

**Comment by tianzhuqiao** [comment]
Perfect. Thanks a lot, @TheJuki.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
