### ISSUE TITLE
actionNext issue with multiple EditText and headers

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#13]
Hey! I'm having a issue with the 'actionNext', take a look at this example:

**REMOVED**

As I'm typing and pressing the next arrow, I'm redirected to the next input, but sometimes the focus is lost. 
My form is basically a bunch of headers and numbers:

```
header {
    title = getString(R.string.mystring)
}
number(MyField.ordinal) {
    numbersOnly = true
    title = getString(R.string.mystring2)
}
```

It looks like when the fields are not visible, android cant put focus on the next field, something like that? I don't know. I wrote "actionNext" in the title of this issue because I saw that your `form_element` has this `imeOptions`:

```
android:imeOptions="actionNext"
```

**Comment by TheJuki** [comment]
I believe it has to do with how Recyclerview renders the views. I attempted to get it to scroll to the bottom and then scroll back to the top but I believe I need to delay that somehow. You can try it manually. Scroll to the bottom and then scroll to the top. ActionNext should be working for all textfields.

**Comment by Fuhrmann** [comment]
That's strange, mine's not working. Even if I scroll down to the bottom of the form, scroll to the top, click in the first field, click next and again, and again, the actionNext stop working at some point, take a look:

![2018-05-01_12-34-20](https://user-images.githubusercontent.com/1160365/39482179-ff829674-4d3b-11e8-811e-c2f0e0f3e9c0.gif)

**Comment by Fuhrmann** [comment]
Ok, I just confirmed that this problem occurs only in the emulator. In my phone it works fine. The emulator is running 7.1.1 and the other 5.1.1  and my phone 7.0.

**Comment by TheJuki** [comment]
That's interesting. Well, as long as nobody runs your app in an emulator you should be good. ;)
It may also have something to do with header rows being focused. I'll do some more testing later today.

**Comment by Fuhrmann** [comment]
Yes, since it's only occurring in the emulator that's ok. In the phone works fine. Thanks.

**Comment by TheJuki** [comment]
I am closing this as the issue only occurs in the Android emulator.
