### ISSUE TITLE
DatePicker Start Date

### ISSUE THREAD

**Issue by wpfilf** [TheJuki/KFormMaster#142]
Dear Juki, thank you so much for this awesome library. It helps us a lot in our Android App.

I was wondering if it would be possible in some way to show the DatePicker Widget used in Date form element with a certain start value?
I mean it is already possible if I set a default dateValue when creating the date form element, but I want to keep the field empty.

**Comment by TheJuki** [comment]
I just released [6.4.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new startDate field works for you. You will need to make sure dateValue is null or just not set.

**Comment by wpfilf** [comment]
Thank you so much Juki! The update works like a charm.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
