### ISSUE TITLE
Feature Request: Change Title View visibility when no title set

### ISSUE THREAD

**Issue by OrlSan** [TheJuki/KFormMaster#147]
## Description

For the included `form_element` layout there is a Linear Layout with ID `formElementMainLayout` as container for the Title text view as well as the ClearableEditText field. I'm implementing a custom component for forms where the Linear Layout gets a vertical orientation and, sometimes, there is no title associated with the element, just a Placeholder (hint).

The vertical space used by the `titleView` is still used although `title = null`. The visibility is unchanged for those cases.

I can see the `titleView`'s visibility is set to `GONE` when when the `editView` is a `SegmentedGroup`, so my proposal is to set the visiblity to `GONE` whenever the `title` is set to `null` or empty string, regarless if the `editView` is a Segmented Group.

I'm prototyping an implementation like the following:

```kotlin
/**
 * Form Element Title
 */
var title: String? = null
    set(value) {
        field = value
        titleView?.let {
            it.text = value
            it.visibility = if (value.isNullOrEmpty()) View.GONE else View.VISIBLE
        }
    }
```

The current implementation sets the `visibility` based on this conditional:

```kotlin
    if (editView != null && editView is SegmentedGroup) {
        it.visibility = if (value.isNullOrEmpty()) View.GONE else View.VISIBLE
    }
```

### Possible impact

I don't know if this change would impact Form Elements layouts or other behaviors. I'd need some help to know the details on this one.

Thank you for reading!
PD: I can send a PR for further discussion if that's fine.

**Comment by TheJuki** [comment]
If you set `displayTitle = true` then it should have the same effect. Setting title to null for SegmentedGroup was requested for hiding the title but I also added the `displayTitle` for the other elements. Let me know if that works for you.

**Comment by OrlSan** [comment]
The `displayTitle` property works perfectly for this use case. I think it is better to close this Issue since the current implementation does exactly this already.

Thank you for your help, Justin!
