### ISSUE TITLE
Suggestion: add an easy way to specify custom layouts per form elements

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#15]
I'll try to explain my problem.

In my application I have a bunch of forms. Around 13 forms. Its a institutional application, so the forms are required to work within the app.

The first form I did, the field labels and the drop down options were not a problem, they were short and concise. In this second form I'm having a problem as you can see in the two images below.

This first image represents the field label, its not that short:

IMAGE REMOVED

When the user clicks the drop down related to this field, the options are shown:

IMAGE REMOVED

There is no way for me to decrease the length of text (only if I could...). So as you can see they are pretty long. When I select one of this options, I got this result, which is not that pretty and the text is incomplete:

IMAGE REMOVED

The same thing happens when the drop down is multi choice.

So my only way out would be to specify that only in this form, only in drop down fields, I want the `formElementValue` to be:

```
android:inputType="textMultiLine"
maxLines="5"
```

I know there is two other ways:

- Overwrite the `form_element`. Downside is that it would be applicable to all forms in my application, to all fields.
- Create a custom field. My problem with custom fields in this package (not that I don't appreciate your work on this) is that its too much boilerplate code to write.

My idea would be something like this:

```
textArea(Fields.MyField.ordinal) {
    title = "Ocupation"
    layout = R.layout.my_text_area_layout
}
```

```
switch<String>(Fields.MyField.ordinal) {
    title = "This is my title"
    onValue = "Yes"
    offValue = "No"
    layout = R.layout.switch_with_additional_text
}
```

Or, if we could specify that for only the form being built, something like this:

```
// Build the form
val formBuilder = form(context!!, my_recycler, cacheForm = true) {
    dropDown<SpinnerOption>(Field.MyField.ordinal) {
        title = "My Field"
        options = listOf()
        hint = getString(R.string.form_selecione)
        dialogTitle = hint

        // Specify custom only for this
        layout = R.layout.special_layout
    }
}


// Specify custom layouts
// Dont mind this sytax, I'm a kotlin beginner
formBuilder.layouts {
	dropDown(R.layout.multiline_dropdown)
	textArea(R.layout.textarea_additional_info)
	text(R.layout.no_text_option)
}
```

What do you think? Is this something possible to implement? Difficult, maybe?

**Comment by TheJuki** [comment]
It may be difficult to replace the entire form element element because of the way the view binder works. But it should not be hard to replace the title, value, and error layouts using the values in the model such as adding variables annotated with `@LayoutRes` and then using this in viewbinder class:

```
 val button = finder.find(model.valueLayout ?: R.id.formElementValue) as Button
```

**Comment by Fuhrmann** [comment]
That should be good! For now I'll either overwrite the default layout and specify that the value layout is multi-line or will implement a custom drop-down field using a custom layout.

**Comment by dhaksddj** [comment]
I'd also be interested in this enhancement! I have quite long strings for questions and answers.

**Comment by TheJuki** [comment]
I just released 3.2.0. Please update your dependency and let me know if the new maxLines variable works for you. I know that this does not fully resolve this issue. However, I could not figure out how to change the layout of an individual form element through the model.

**Comment by Fuhrmann** [comment]
![image](https://user-images.githubusercontent.com/1160365/40211249-99556f5a-5a17-11e8-8b84-d6498622f94e.png)

Working **great**! Thanks again.

**Comment by TheJuki** [comment]
I just released [4.2.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new FormLayouts class works for you. I know that maxLines resolved your issue but this update fully resolves "specify [layouts] for only the form being built".

**Comment by Fuhrmann** [comment]
Hey @TheJuki I'll test this asap and give you a feedback, thanks!!

**Comment by Fuhrmann** [comment]
Ok, this is great! Working as intended. Many thanks!! 👍 👍   (using 4.4.0)
