### ISSUE TITLE
Input-Mask

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#151]
Hi there,

It would be a improvement of the usablity if a field could have an input mask. This can be really helpful for the input of phone (+49 123 456 789) or iban (DE 12 1234 5679 1011 1213) numbers.

Here is a great lib which does this really well: https://github.com/RedMadRobot/input-mask-android

Looking forward to your feedback. :-)

Best,
Daniel

**Comment by atomengine** [comment]
I've created this as a custom field if you'd like?

**Comment by darkwood-studios** [comment]
> I've created this as a custom field if you'd like?

Yes, you can share your code here, I will take a look. Maybe @TheJuki can use something of it, too.

Nevertheless the mask feature would be a great feature for all input fields. I should not be necessary to implement a custom field for each type of mask.

**Comment by darkwood-studios** [comment]
@atomengine  @TheJuki 
Any news on this issue? I'm getting a huge amount of feedback because of the bad UX of the IBAN field. A input mask could have some huge benefits to the usablity of form fields.

**Comment by TheJuki** [comment]
Sorry for the delay on this.

I just released [6.4.4](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new inputMaskOptions property works for you. This is using RedMadRobot/input-mask-android.

**Comment by darkwood-studios** [comment]
Hey @TheJuki 

Works great! Thank you again for your fantastic work.
