### ISSUE TITLE
SearchBar for DropDown

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#159]
Hi there,

in some case I have a huge amount of select options within my drop down fields. I think it could be a big relief if there is an optional search bar on top of the select list. (to filter the options while typing)

One great lib for search bars is https://github.com/mancj/MaterialSearchBar maybe it's possible to use it for this case.

I'm looking forward for your help.

Best regards,
Daniel

**Comment by TheJuki** [comment]
Could you use the existing autoComplete element for this? If you need to load the options through an API call, you can do so in a custom ArrayAdapter:

https://github.com/TheJuki/ExampleKotlinApp/blob/master/app/src/main/java/com/thejuki/example/adapter/array/ContactAutoCompleteAdapter.kt#L57

**Comment by darkwood-studios** [comment]
Great idea. I use autoComplete instead. Thx. :-)

**Comment by sarbogast** [comment]
I can't make this work while loading options in the background. With DropDown, I managed to refresh the list by calling reInitDialog on the form element, but I don't have such a refresh method for autocomplete, at least none that is available before API 29

**Comment by TheJuki** [comment]
This is from my Example project using this library:

https://github.com/TheJuki/ExampleKotlinApp/blob/master/app/src/main/java/com/thejuki/example/api/RestService.kt#L47
https://github.com/TheJuki/ExampleKotlinApp/blob/master/app/src/main/java/com/thejuki/example/api/ApiClient.kt#L123
https://github.com/TheJuki/ExampleKotlinApp/blob/master/app/src/main/java/com/thejuki/example/adapter/array/ContactAutoCompleteAdapter.kt#L57

Does this help?

**Comment by sarbogast** [comment]
Yes! I think I was missing the filter part. Thanks.
