### ISSUE TITLE
Issue with recycler view recycling?

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#16]
This is part of my form (it has more fields):

```
number(Field1.ordinal) {
    title = getString(R.string.field_1)
    hint = getString(R.string.select)
    required = true
}
number(Field2.ordinal) {
    title = getString(R.string.field_2)
    numbersOnly = true
    hint = getString(R.string.select)
    required = true
}
``` 

I set to **not** cache the form:

```
val formBuilder = form(this, recycler_fields, cacheForm = false) {
```

And I got this result:

![2018-05-06_14-22-51](https://user-images.githubusercontent.com/1160365/39676464-4e6476c6-5139-11e8-8002-361f56a5ed5b.gif)

If I set `cacheForm` to `true` everything works fine, 

This is the layout of my form activity:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_fields"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:descendantFocusability="beforeDescendants"
        android:orientation="vertical"
        app:layoutManager="android.support.v7.widget.LinearLayoutManager" />

</LinearLayout>
```

Is this maybe related to the way recycler works?

**Comment by Fuhrmann** [comment]
Ok, this behavior only happens when I run the application inside the emulator. The android version is 5.1, but the problem is I can't test on a physical device with the same API because I don't have one.

My physical device is running 7.0 and everything works fine. Do you happen to have a physical device running 5.1 or 5.0 to test? Or even if you could setup an emulator in your own machine, because as you noticed, my last open issues in this project are only happening inside the emulator.

**Comment by TheJuki** [comment]
I am not sure how to fix this. Caching the form does not seems to have any performance issues as far as I can tell. 

https://github.com/vivchar/RendererRecyclerViewAdapter/issues/15

**Comment by dhaksddj** [comment]
I'm not sure if this is related but I have quite a long form and when the first element has scrolled off the screen and then I clear the form, the first element has not been cleared down. This is what I see with cache = false. I tried again with cache = true and the first element was cleared.

**Comment by TheJuki** [comment]
Yeah. RecyclerView is not very good at updating the form elements when they are not cached. In the latest releases I set cacheForm = true by default.

**Comment by TheJuki** [comment]
This has been "fixed". CacheForm is true by default now to fix the RecyclerView weirdness. I am closing this issue. However, feel free to reopen.
