### ISSUE TITLE
Layout of SwitchFormElement looks buggy with long labels

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#161]
## Description

The layout of switches with longer labels looks strange, because it has line breaks on the left and much space on the right (see example attached)

### Expected behavior

The Layout should not be splittet in 50/50 for a switch, because there is much more space for the label. 70/30 or 80/20 should be a better ratio.

### Actual behavior

The layout is splitted in 50% for the label and 50% for the switch and looks buggy

### Steps to reproduce the bug

Create s switch with a longer label.

### KFormMaster version

* Version: Latest

### System information

* Android OS: 10/Latest
* Issue in Emulator: Yes
* Issue in physical device: Yes

![kform_bug](https://user-images.githubusercontent.com/8148815/70723699-a04c2280-1cf9-11ea-9817-7bd07a0406d8.png)

**Comment by TheJuki** [comment]
I just released [6.4.7](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new layout weights work for you.

**Comment by darkwood-studios** [comment]
Looks great now. Thank you :-)
