### ISSUE TITLE
Layout issue for segmented Buttons

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#163]
Hi there,

on some devices I have a strange layout issue for segmented buttons. Please see the problem attached.
![layout_problem](https://user-images.githubusercontent.com/8148815/71613014-4cb85080-2ba4-11ea-944c-4cf916bfab79.png)

Best regards,
Daniel

**Comment by darkwood-studios** [comment]
Additional info.

On the screen is some dirty hack from me active. (it adds an line break to the short label, if the other button has a line break) - I think its better reproducible if you use an other example.

"Here is some long label" and "short label" should show the issue.

I would expect, that all buttons will get the same size. It would look best if the shorter text will be positioned in center

On this shot you see the difference:

![example](https://user-images.githubusercontent.com/8148815/72333092-88cad580-36bb-11ea-9bc4-070d523bfaf1.png)

**Comment by TheJuki** [comment]
I just released [6.5.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if using radioGroupWrapContent, radioButtonWidth, and radioButtonHeight  work for you. See: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L594

**Comment by darkwood-studios** [comment]
hm, i don't thing that this fixes the problem.

"radioGroupWrapContent" results in an new layout issue - all buttons are floating left instead of fill space

**Comment by darkwood-studios** [comment]
Hey @TheJuki  any news on this?

**Comment by TheJuki** [comment]
I just released [6.5.5.](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is working now. Sorry for the long delay on this. Make sure fillSpace is true.

**Comment by darkwood-studios** [comment]
works great. thank you. :-)
