### ISSUE TITLE
titleIconPadding not working

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#164]
Hi there,

the new titleIconPadding is not working.

titleIconPadding = 0 looks exactly like titleIconPadding = 30

```
number(FormField.TYPE_ZIP) {
                title = "Postleitzahl"
                required = true
                value = "12345
                numbersOnly = true
                clearOnFocus = true
                maxLength = 5
                titleIconLocation = IconTextView.Location.RIGHT
                titleIcon = ContextCompat.getDrawable(ctx, R.drawable.ic_check_green)
                titleIconPadding = 50
            }
```

![titleview](https://user-images.githubusercontent.com/8148815/71718593-fa816480-2e1b-11ea-8c62-10d232427d95.png)

I would expect that the space between icon and label changes if i change the padding.

**Comment by TheJuki** [comment]
I just released [6.5.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new padding property works for you. You can use the new padding property to squeeze the icon and text together. See: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L261

**Comment by darkwood-studios** [comment]
Hi @TheJuki 
When I use titleIconPadding = 0 I expect that the icon is very close to the title. But there is still some huge space between. Do you have an idea?

**Comment by TheJuki** [comment]
You have to use titlePadding to squeeze them together. Apparently that is the only way with when using setCompoundDrawables.

**Comment by darkwood-studios** [comment]
I think that done. I'm closing.
