### ISSUE TITLE
Multiline text field shows just one line, and its height is too small

### ISSUE THREAD

**Issue by janosvajda** [TheJuki/KFormMaster#166]
Hi, 

firstly, thank you for this fantastic library. It is really exciting. 

I noticed a minor issue in text-field, and reported it here. 

## Description

If I create a text element with setMaxLines (text_field.setMaxLines(3); for example) then multi-line text field shows just one and half line, and its height going to be too small, and also scrolling is not working so you cannot really do scrolling, and you cannot see the whole text in the textarea. 

Attached screenshot:

![longtextIssue](https://user-images.githubusercontent.com/982784/71950533-79d1b800-31cf-11ea-98cf-f3eb1f46d41e.jpg)

### Expected behavior

Multiline text fileds should show a scrollbar and/or should get setHeight method, or something similar solution.

### Actual behavior

It shows just one line, text cannot be scrolled properly, and other part of texts are hidden.

### Steps to reproduce the bug

1. Create a text field
2. Set title
3. use setMaxLines(3)

### KFormMaster version

* Version: Latest

### System information

* Android OS: 8.1/Latest
* Issue in Emulator: Yes
* Issue in physical device: Yes

**Comment by TheJuki** [comment]
I am not seeing this issue. Are you using the textArea element?

<img width="328" alt="Screen Shot 2020-01-08 at 7 09 36 AM" src="https://user-images.githubusercontent.com/2180227/71980614-199a4080-31e6-11ea-8de4-551b45eb3cbf.png">

**Comment by janosvajda** [comment]
Hi,

This is the code:

`        FormSingleLineEditTextElement text_field = new FormSingleLineEditTextElement();
        text_field.setTitle(addEditTextField);
        text_field.setValue("");
        text_field.setRequired(true);
        text_field.setInputType(ConsultationQuestionnaireForm.INPUT_TYPE_TEXT);
        text_field.setMaxLines(3);
        text_field.setCenterText(true);
        elements.add(text_field);
`

I might need to just  use another element?

Thanks,
Janos

**Comment by TheJuki** [comment]
Use FormMultiLineEditTextElement instead

**Comment by janosvajda** [comment]
That is working perfectly. Thanks a lot.

It is off this topic, but may I ask here that is there any way how you can change field title's font size and setDialogTitle's font size? I have extra long text titles and just half of the text are appearing in FormPickerDropDownElement element. Sorry, this is not relating to this topic.

Thanks.

**Comment by TheJuki** [comment]
<resources>
    <dimen name="headerTextSize">15sp</dimen>
    <dimen name="elementTextTitleSize">16sp</dimen>
    <dimen name="elementTextValueSize">16sp</dimen>
    <dimen name="elementErrorTitleSize">16sp</dimen>
    <dimen name="elementRadioCornerRadius">5dp</dimen>
    <dimen name="elementRadioStrokeBorder">1dp</dimen>
    <dimen name="elementRadioPadding">10dp</dimen>
    <dimen name="elementImageProgressBarLength">60dp</dimen>
    <dimen name="elementImageProgressBarWidth">10dp</dimen>
    <dimen name="elementImageProgressRimWidth">10dp</dimen>
    <dimen name="elementImageProgressTextSize">20sp</dimen>
</resources>

These are the dimensions you can override. Currently, the dialog is not setup to change the font sizes.

**Comment by janosvajda** [comment]
Thanks a lot. :)

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
