### ISSUE TITLE
title icon not working for button

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#167]
Hi there,

I want to place some badge icon to my button. This is my code

button {
                value = "My Button Title"
                valueObservers.add { _, _ ->
                    doSomething()
                }
                titleIcon = ContextCompat.getDrawable(ctx, R.drawable.ic_new)
            }

But my icon will not show up. Any ideas?

**Comment by TheJuki** [comment]
Buttons don't have title views but I can use the titleIcon to set the button drawable.

**Comment by darkwood-studios** [comment]
yeah I think that could work. thank you.

**Comment by TheJuki** [comment]
I just released [6.5.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if setting the titleIcon for the button works for you. You can also use the new padding property to squeeze the icon and text together. See: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L609

**Comment by darkwood-studios** [comment]
This works great. I close this issue. Thanks!

I noticed that you have changed the layout of the button. (before they was centered and bold) - I added centerText = true to center the text again. Do you have a idea how I can set the text style back to "bold"?
