### ISSUE TITLE
Changing dropDown options dinamically while form is cached

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#17]
Since issue #16 is happening, I always have to create a form and set `cacheForm` to `true`. But this way, I can't change the options of a drop down dynamically.

These are the steps my form implements:
- User select OPTION1 from DROPDOWN1
- Application set options of DROPDOWN2  to (A, B, C)
- User select OPTION2 from DROPDOWN1
- Application set options of DROPDOWN2  to (A, B)

Since the form is cached, the options are not being updated. If you need a gif of this happening, let me know (or need any help)!

Maybe you could give us a method that we can manually invalidate the options of a cached dropdown something like this:

```
// If the form is cached, we have to manually call invalidate
val items = ...
val dropdown = getFormElement<FormPickerDropDownElement<MyItem>>(Fields.Field1)
dropdown.setOptions(items)
dropdown.invalidate()
```

I think this is good, because in my case I want my form to be cached, because it's too many fields. But I want the possibility of changing everything dinamically. Does this makes sense for you?

Thanks.

**Comment by TheJuki** [comment]
The alert dialog that is shown/hidden stores the options and selected items. I will need to add a way to re-init that alert dialog.

**Comment by TheJuki** [comment]
This has been added to version 3.1.0. Please update your dependency. 
```
val items = ...
val dropdown = formBuilder.getFormElement<FormPickerDropDownElement<MyItem>>(Fields.Field1)
dropdown.setOptions(items)
dropdown.reInitDialog(this /* context */, formBuilder)
```
Let me know if works for you.

**Comment by Fuhrmann** [comment]
Yes, working great. Thank you!
