### ISSUE TITLE
FormImageElement opens camera/gallery again after selecting image edit view opens then gallery opens agin

### ISSUE THREAD

**Issue by gohun04** [TheJuki/KFormMaster#172]
On one of my test devices the FormImageElement  bugs out and opens the camera or gallery again on top of the view after it enters edit mode. 

My Device is a Galaxy Note 10 android version 10

**Comment by magherita** [comment]
Hi,
has any progress been made regarding this bug?
I am using this library in a client app and would love to know the latest update please

**Comment by TheJuki** [comment]
I just released [6.5.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this has been fixed for you.

**Comment by TheJuki** [comment]
I have submitted a PR to the ImagePicker repo to fix the issue.: https://github.com/Dhaval2404/ImagePicker/pull/63

For now, the fix is in my fork of the repo. JitPack is providing the build with the fix.

**Comment by magherita** [comment]
> 
> 
> I just released [6.5.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this has been fixed for you.

Hi,
I updated my dependency to 6.5.2 and I can confirm this bug has been resolved.
Thank you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
