### ISSUE TITLE
ERROR: Failed to resolve: com.github.TheJuki:ImagePicker:1.11

### ISSUE THREAD

**Issue by anggit97** [TheJuki/KFormMaster#179]
there is bug when installing the latest version of this library (6.5.2), it show error 
`ERROR: Failed to resolve: com.github.TheJuki:ImagePicker:1.11
Show in Project Structure dialog
Affected Modules: app`

but its working okay in previous version (6.5.1).

**Comment by TheJuki** [comment]
https://github.com/TheJuki/KFormMaster/blob/master/build.gradle#L27

You may need to add:
`maven { url "https://jitpack.io" }` to your root build.gradle repository list.

This is just temporary until the original ImagePicker project is updated with the fix: https://github.com/Dhaval2404/ImagePicker/pull/63

**Comment by anggit97** [comment]
okay thanks man

**Comment by TheJuki** [comment]
Updated README.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.

**Comment by anggit97** [comment]
thanks for fast response

**Comment by ControlAdad** [comment]
Although I've included jitpack, I still receive this error :

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.TheJuki:ImagePicker:1.11.
     Required by:
         project :app > com.thejuki:k-form-master:6.5.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

```

**Comment by TheJuki** [comment]
> Although I've included jitpack, I still receive this error :
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
>    > Could not find com.github.TheJuki:ImagePicker:1.11.
>      Required by:
>          project :app > com.thejuki:k-form-master:6.5.2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5s
> ```

I am not seeing this as an issue. I use this library in an Example App and the latest version built successfully. 

https://github.com/TheJuki/ExampleKotlinApp

**Comment by zl910627** [comment]
still not resolved, and it is happening on latest version - 6.5.6

**Comment by TheJuki** [comment]
I just released [7.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this issue is resolved. I moved my fixed repo into JCenter instead of JitPack.

**Comment by zl910627** [comment]
Thank you @TheJuki 
The issue fixed at v7.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
