### ISSUE TITLE
Are "File Picker", "Ratings" and "Signature Pad" available in this library ?

### ISSUE THREAD

**Issue by sathanu** [TheJuki/KFormMaster#181]
Are "File Picker", "Ratings" and "Signature Pad" available in this library ?

**Comment by TheJuki** [comment]
No. Those are not current form elements in this library.

**Comment by sathanu** [comment]
This library almost reduced my ui work.
I have to place two text box horizontally in a row. 
How can we do with this library?

**Comment by TheJuki** [comment]
https://thejuki.github.io/KFormMaster/custom/element/

https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/res/layout/form_element_custom.xml
https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/custom/model/FormCustomElement.kt

You can create a custom form element for that.

**Comment by sathanu** [comment]
Thanks
