### ISSUE TITLE
Image Row

### ISSUE THREAD

**Issue by ReyesWei** [TheJuki/KFormMaster#185]
## Description

Hi, I can't find a way to remove the textView "Change Image" 
( android:id="@+id/formElementImageLabel" ) In FormImageElement.
The way I use it now is to override \<string name="form_master_picker_change_image">\</string>,is this way right?

Q2: In my another situation,I want to show title in left and image in right  read only, is there a way to do this or I need to customize by myself?

Q3: By the way, is there a way I can edit the image'size  In FormImageElement (default is 175X175)

thank you.

**Comment by TheJuki** [comment]
I just released [6.5.3](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency.

I added the following properties to FormImageElement:
- displayImageWidth and displayImageHeight to change the size of the image displayed on the form
- changeImageLabel to set the text of the label that currently is set to "Change Image"
- showChangeImageLabel to show/hide the "Change Image" label

I have not set up the layout for the title view. I'll try this out later.

**Comment by ReyesWei** [comment]
Thank you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
