### ISSUE TITLE
Disabling form elements

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#19]
Hi,

I'm building a dynamic form and once a user has answered a question, I would like to make that question uneditable.

How would I accomplish this? I can tell if they have answered the question before but not sure what property to set on the elemnts. I tried options = listOf() but that didn't work, the original options still appeared.

**Comment by TheJuki** [comment]
```
val dropdown = formBuilder.getFormElement<FormPickerDropDownElement<MyItem>>(Fields.Field1)

dropdown.editView?.let {
	it.isEnabled = false
	it.setTextColor(ContextCompat.getColor(context, R.color.colorFormMasterElementTextDisabled))
	it.isFocusable = false
	it.setRawInputType(InputType.TYPE_NULL)
}
```

I'll need to add code to do this for you by adding a "disabled" variable to the Base Model. However, you can try that code and let me know if that works for you.

**Comment by TheJuki** [comment]
This has been added to version 3.1.0. Please update your dependency. You can now just set model.enabled = false. Let me know if works for you.

**Comment by dhaksddj** [comment]
Thanks! Seems to work.
