### ISSUE TITLE
FormElement Title Width

### ISSUE THREAD

**Issue by wenyang9319** [TheJuki/KFormMaster#191]
This is not a bug report. 
Just want to ask if there's a way of editing the display width of the title label?

Because I want to expand the display width of the title label in a few Form Element so writing a custom class is not a good way to do so.

**Comment by wenyang9319** [comment]
Besides that, how can i set maxLines on the title label of dialog builder?
Is there any way to customise the dialog? Since the we can't set maxLines through alert dialog theme.

**Comment by TheJuki** [comment]
I just released [6.5.6](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if setting dialogTitleCustomView works for you.

**Comment by wenyang9319** [comment]
It is working, thanks
