### ISSUE TITLE
rightToLeft should not be default

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#193]
Hi there,

I just updates from 6.4 to latest 6.5 and all of my buttons are now "Gravity.END". I found in BaseFormElement that the parameter "rightToLeft" is default true, so the gravity changed to end.

Default value in android is rightToLeft=false and gravity=Gravity.START, so I think this should be the default for this library, too.

Or is there any reason that all buttons are gravity end now?

Best regards,
Daniel

**Comment by TheJuki** [comment]
I just released [7.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if button text is now centered by default. The new property editViewGravity replaces both rightToLeft and centerText.

When I added icons to the buttons I needed to use rightToLeft and centerText. However, it makes more sense to just have the one gravity property and give the button element an override default to Gravity.CENTER.

**Comment by TheJuki** [comment]
The form elements are still defaulted to Gravity.END since the original library did that. Setting each element's editViewGravity property to Gravity.START is a solution for now.

**Comment by darkwood-studios** [comment]
Buttons are looking great now. 👍
