### ISSUE TITLE
FormButtonElement should have centerText=true

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#194]
Hi there,

in 6.4 all button texts were centered. Since 6.5 centerText is false by default. I think the centered version is a much better one, because this is an android default.

Best,
Daniel

**Comment by TheJuki** [comment]
I just released [7.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if button text is now centered by default. The new property editViewGravity replaces both rightToLeft and centerText.

**Comment by darkwood-studios** [comment]
Hi @TheJuki 

works great, thank you. 👍
