### ISSUE TITLE
How to underline a text in TextView

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#195]
Hi there, 

is there a way to underline a value in a TextView? For example:

textView {
    title = "Some title"
    value = "Some value"
    underlineValue = true
}

I've already tried to use (formBuilder.getFormElement<FormTextViewElement>(1).itemView as TextView?) but this view  is always NULL

**Comment by TheJuki** [comment]
I just released [7.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if setting the new property editViewPaintFlags to Paint.UNDERLINE_TEXT_FLAG works for you.

**Comment by darkwood-studios** [comment]
Perfect one! Thank you for that great work!
