### ISSUE TITLE
FormTextViewElement onClick not working on EditText

### ISSUE THREAD

**Issue by soareseneves** [TheJuki/KFormMaster#197]
## Description

FormTextViewElement onClick doesn't work if I tap on the text.

### Expected behavior

It should trigger **model.onClick** when I am tapping the EditText

### Actual behavior

It's not triggering the onClick event

### Steps to reproduce the bug

Add a FormTextViewElement to your form
Set the onClick listener with some sort of alert

### KFormMaster version

* Version: Latest

The issue is on this line: https://github.com/TheJuki/KFormMaster/blob/ef783dd303cb4dbb7ebfe3fec490692d3d1199aa/form/src/main/java/com/thejuki/kformmaster/view/FormTextViewViewBinder.kt#L40

In order for the onClick to work on the EditText you need to set the isEnabled property to true

I tested here and it works.

**Comment by TheJuki** [comment]
I just released [8.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this issue is resolved for you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
