### ISSUE TITLE
Save and restore an input value while scroll

### ISSUE THREAD

**Issue by vivchar** [TheJuki/KFormMaster#2]
Hi, thanks for using my library.

You could save and restore an input value while scroll, please see how to implement it:
[Short Recommendations](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Recommendations-for-the-View-States)
[Example Source Code](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/master/example/src/main/java/com/github/vivchar/example/pages/simple/ViewStateFragment.java)
[Example Gif](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/master/example/view-state.gif)

**Comment by TheJuki** [comment]
This library is not using a nested RecyclerView. The elements seems to save and restore on scroll just fine with the standard ViewBinder.

**Comment by vivchar** [comment]
@TheJuki No, it does not save, it works fine while you have a small list.
Try to add about ~30 items (you will see it when a recycler view items are reused).

**Comment by TheJuki** [comment]
Okay. Is there a way to override the createViewState and createViewStateID for a ViewBinder and not a CompositeViewBinder?

**Comment by vivchar** [comment]
yea, please use the other constructor:
[ViewBinder:70](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/master/rendererrecyclerviewadapter/src/main/java/com/github/vivchar/rendererrecyclerviewadapter/binder/ViewBinder.java#L70)
```
public ViewBinder(@LayoutRes final int layoutID,
	                  @NonNull final Class<M> type,
	                  @NonNull final Binder<M> binder,
	                  @Nullable final ViewStateProvider<M, ViewHolder> viewStateProvider) {
		super(type);
		mLayoutID = layoutID;
		mBinder = binder;
		mViewStateProvider = viewStateProvider;
	}
```

**Comment by TheJuki** [comment]
var viewBinder = ViewBinder(R.layout.form_element_header, FormHeader::class.java, FormViewStateProvider()) { model, finder, _ ->

This is not working. It is not matching that constructor. Should @NonNull final Binder<M> binder be the last argument in your constructor?

**Comment by vivchar** [comment]
No, it is not last argument
```
new ViewBinder<>(
			R.layout. form_element_header,
			FormHeader.class,
			(model, finder, payloads) -> {

			},
			new FormViewStateProvider()
)
```

**Comment by TheJuki** [comment]
var viewBinder = ViewBinder(R.layout.form_element_header, FormHeader::class.java, { model, finder, _ ->
        val textViewTitle = finder.find(R.id.formElementTitle) as AppCompatTextView

        textViewTitle.text = model.title
    }, FormViewStateProvider<FormHeader>())

Yeah. So far this is working.

**Comment by TheJuki** [comment]
`class FormViewState(holder: ViewHolder) : ViewState<ViewHolder>
{
    private var itemViewState: SparseArray<Parcelable> = SparseArray()

    init {
        holder.itemView.isSaveEnabled = true
        holder.itemView.saveHierarchyState(itemViewState)
    }

    override fun restore(holder: ViewHolder) {
        holder.itemView.restoreHierarchyState(itemViewState)
    }
}`

I implemented the ViewState. I am not sure what I need to be saving and restoring though.

**Comment by vivchar** [comment]
Step 1: Add the getID() method to your model:
```
public class EditViewModel implements ViewModel {

	public int getID() {
		return mID; /* uniqueID of your model */
	}
}
```

Step 2: Create a ViewState for your ItemType:
```
public class EditViewState implements ViewState<ViewHolder> {

	private final String mEnteredText;

	public EditViewState(ViewHolder holder) {
		EditText editText = holder.getViewFinder().find(R.id.your_edit_text);
		mEnteredText = editText.getText().toString();
	}

	@Override
	public void restore(@NonNull final ViewHolder holder) {
		holder.getViewFinder().setText(R.id.your_edit_text, mEnteredText);
	}
}
```

Step 3: Create ViewStateProvider for your ViewModel:
```
public class EditViewStateProvider implements ViewStateProvider<EditViewModel, ViewHolder> {
	
	@Override
	public ViewState createViewState(@NonNull final ViewHolder holder) {
		return new EditViewState(holder);
	}

	@Override
	public int createViewStateID(@NonNull final EditViewModel model) {
		return model.getID(); /* using the ID of ViewModel as a ID of ViewState */
	}
}
```

Step 4: Create ViewBinder for your ViewModel:
```
public class EditViewBinder extends ViewBinder<EditViewModel> {

	public EditViewBinder() {
		this(
				R.layout.your_edit_text_item_layout,
				EditViewModel.class,
				(Binder<EditViewModel>) (model, finder, payloads) -> {
					/* your binding */
				},
				new EditViewStateProvider()
		);
	}

	public EditViewBinder(final int layoutID,
	                      @NonNull final Class<EditViewModel> type,
	                      @NonNull final Binder<EditViewModel> binder,
	                      @Nullable final ViewStateProvider<EditViewModel, ViewHolder> viewStateProvider) {
		super(layoutID, type, binder, viewStateProvider);
	}
}
```

Step 5 Register your ViewBinder:
```
adapter.registerRenderer(new EditViewBinder());
```

**Comment by TheJuki** [comment]
[AddViewStates branch](https://github.com/TheJuki/KFormMaster/tree/AddViewStates)

I added a new branch that adds the ViewStateProviders to the ViewBinders. I am having issues with the "popup" fields. Fields that require a dialog revert to the saved class variable in the ViewState class when the dialog is closed. I need the ViewState to re-init/save when the dialog is closed.

**Comment by TheJuki** [comment]
In the old code it was necessary to call refreshView() to call this.formAdapter!!.notifyDataSetChanged() when elements like the pickers were changed. However, the text of editTextValue and textViewError can just be set instead of using notifyDataSetChanged. Closing this issue.
