### ISSUE TITLE
Issue with DatePicker

### ISSUE THREAD

**Issue by NoeAlkar** [TheJuki/KFormMaster#20]
Hi,

it looks like DatePicker adds a month to the value shown in the form. I.e. if you pick march 15th 2018 it'll show 6/15/2018 instead of 5/15/2018, but if you tap again the control the picker'll show the correct value.

Maybe this has to do with the lines 54 and 78 of FormPickerDateViewBinder.kt?

**Comment by TheJuki** [comment]
You’re right. About to release 3.1.2 to fix that.

**Comment by TheJuki** [comment]
I had no idea that a commit could close an issue...Anyway, I just released 3.1.2. Please update your dependency and let me know it this has been resolved.

**Comment by NoeAlkar** [comment]
Thanks for answering so quickly, it's working ok now!
