### ISSUE TITLE
Header & Label background color 

### ISSUE THREAD

**Issue by floriangbh** [TheJuki/KFormMaster#201]
Hello, 

## Description

I can't find a way to change the background of some form element? 

### Expected behavior

Use `backgroundColor`properties to change background color.

### Actual behavior

```kotlin
header {
    backgroundColor = R.color.colorBackground
}
```

Provide the wrong color.

<img width="1138" alt="Screenshot 2020-08-05 at 15 22 19" src="https://user-images.githubusercontent.com/14054997/89418533-79cb7380-d730-11ea-94f1-d75d16d59036.png">

Maybe is there another way to change the background of le linearLayout ? 

### KFormMaster version

* Version: Latest

### System information

* Android OS: 10

Thanks

**Comment by Goule** [comment]
Same question here :)

**Comment by TheJuki** [comment]
I just released [8.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this issue is resolved for you.

**Comment by floriangbh** [comment]
It working great now ! Thanks.
