### ISSUE TITLE
upgrade RendererRecyclerViewAdapter dependency

### ISSUE THREAD

**Issue by vivchar** [TheJuki/KFormMaster#214]
Hi, If you are still using RendererRecyclerViewAdapter, please upgrade to [last version](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Steps-for-migration-to-3.0) 

I fixed ViewState issue:
https://github.com/TheJuki/KFormMaster/issues/16
https://github.com/vivchar/RendererRecyclerViewAdapter/issues/15

**Comment by TheJuki** [comment]
Upgraded to latest version in 8.0.0.
