### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by floriangbh** [TheJuki/KFormMaster#220]
## Description

My crash reporting tool reporting a crash.

`Unable to instantiate activity ComponentInfo{com.swish.swishLive/com.thejuki.kformmaster.FormActivityTest}: java.lang.ClassNotFoundException: Didn't find class ` 

### Expected behavior

No crash :D 

### KFormMaster version

* Version: Latest

### System information

* Android OS: 8.1/Latest

Is there any class to put in the R8 proguard rules ? 

Thanks

**Comment by TheJuki** [comment]
I just released [8.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this issue is resolved for you.

**Comment by floriangbh** [comment]
Ok thanks, I've updated to 8.0.0 and will re open if the issue come back.
