### ISSUE TITLE
Use ListAdapter/notifyItem*Changed instead of notifyDataSetChanged

### ISSUE THREAD

**Issue by VincentJoshuaET** [TheJuki/KFormMaster#228]

**Comment by TheJuki** [comment]
I just released [8.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is now working for you.

NOTE: I have pushed the latest version to Maven Central (mavenCentral()) and changed the group id to "com.github.thejuki".

```
implementation "com.github.thejuki:k-form-master:8.2.1"
```

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
