### ISSUE TITLE
Logo Proposal for KFormMaster

### ISSUE THREAD

**Issue by area55git** [TheJuki/KFormMaster#23]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project KFormMaster.

I will be pleased to collaborate with you.

**Comment by TheJuki** [comment]
That would be awesome! I created the current logo in like 5 minutes using the Roboto font.

**Comment by area55git** [comment]
Perfect..! I am very enthusiastic to design a Profesional Logo for your project, in a day or two I will send you a proposal.

If you have some ideas, suggestions as to style or colors would be great to be able to start.
I also need a brief summary of KFormMaster to get a better idea.

**Comment by TheJuki** [comment]
Red, Orange, Purple, and Blue would be good colors. The Kotlin logo uses a gradient of those colors. KFormMaster is a form builder that uses a RecyclerView to programmatically add form elements such as text fields, headers, buttons, and dropdowns.

**Comment by area55git** [comment]
Hi @TheJuki, This is my proposal for your logo

[![LOGO_PROPOSAL_FOR_KFORMMASTER.jpg](https://s31.postimg.cc/iedul8du3/LOGO_PROPOSAL_FOR_KFORMMASTER.jpg)](https://postimg.cc/image/phlq0uj9j/)


What you think? You like?

**Comment by TheJuki** [comment]
[![Logo](https://snag.gy/lIQvXx.jpg)](https://snag.gy/lIQvXx.jpg)

I like this one the best but I think it needs some color. (Soft colors)

#7d6fe3 and #0094d4 are used in the current logo.

**Comment by TheJuki** [comment]
I love it! Go ahead and create a pull request for it.

**Comment by area55git** [comment]
Perfect..!!! I'm going to prepare the logo for other formats (PNG, JPG, SVG), tomorrow I'll send it to you.

**Comment by Fuhrmann** [comment]
Really good choice! Good work @area55git!

**Comment by area55git** [comment]
Thank @Fuhrmann, I appreciate your comment.

**Comment by area55git** [comment]
Hi @TheJuki, in the link are the final logos in various formats. I loved collaborating with your project, remember to merge the PR.

# [FILE DOWNLOAD](https://drive.google.com/open?id=1NE5_y9Qs6fjyaFCgo4NuD9va9JTyKvpO)

[![DERECHOS.jpg](https://s31.postimg.cc/8yq7qdnu3/DERECHOS.jpg)](https://postimg.cc/image/mfn698y5j/)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Comment by TheJuki** [comment]
I have been waiting for these. Thanks! I updated my README using the image in your fork since I was having issues getting the correct logo size.

**Comment by area55git** [comment]
Enjoy it..!!!!
