### ISSUE TITLE
Build failed: Duplicate key: (row=string, column=action_cancel)

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#231]
When I build the app with gradle I see this error:

Duplicate key: (row=string, column=action_cancel), values: [UNDEFINED string action_cancel = 0x7f110027, UNDEFINED string action_cancel = 0x7f110021].

I searched the entire project and found the "action_cancel" string only in com.github.dhaval2404.imagepicker.util.DialogHelper which is used by the KFormMaster library.

I have the problem with 7.0 and with the new 8.1

Do you have any idea how to solve this?

**Comment by TheJuki** [comment]
I updated by example app to the latest version and had no issues: https://github.com/TheJuki/ExampleKotlinApp/commit/e9a879c0459c36c94d789f9d4092efbfd032e888#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R61

What SDK, gradle, and kotlin versions are you using?

**Comment by darkwood-studios** [comment]
Hey,

I figured out that the GeniusScan SDK (https://geniusscansdk.com/) is using the same string "action_cancel" - that results in a conflict. If I remove the GSSDK or the kFormMaster everything works, but both libraries can't work together. Are you able to change the name of the string? Maybe with a prefix?

**Comment by TheJuki** [comment]
I just released [8.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is now working for you.

NOTE: I have pushed the latest version to Maven Central (mavenCentral()) and changed the group id to "com.github.thejuki".

```
implementation "com.github.thejuki:k-form-master:8.2.1"
```

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
