### ISSUE TITLE
Not firing onValueChanged on FormSegmentedElement

### ISSUE THREAD

**Issue by ShinJoonSeob** [TheJuki/KFormMaster#239]
Hi,

I checked that onValueChanged is not working in FormSegmented while testing this project.

This is a problem that sometimes occurs on more than 3 segments.

I'm using version 8.1.0

Thank you!

**Comment by TheJuki** [comment]
I just released [8.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is now working for you.

NOTE: I have pushed the latest version to Maven Central (mavenCentral()) and changed the group id to "com.github.thejuki".

```
implementation "com.github.thejuki:k-form-master:8.2.1"
```

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
