### ISSUE TITLE
displayValueFor in FormPickerMultiCheckBoxElement

### ISSUE THREAD

**Issue by bb-art** [TheJuki/KFormMaster#241]
Hi!
Thanks for your nice working lib

Would it be possible to implement the displayValueFor function in the FormPickerMultiCheckBoxElement too? 
At the moment it uses option.toString() only.

thanks!

**Comment by TheJuki** [comment]
Thanks for your PR. Since T is the list itself, I needed to add a new generic to define that inner class. I'll push this and other fixes later today.

**Comment by TheJuki** [comment]
I just released [8.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is now working for you.

NOTE: I have pushed the latest version to Maven Central (mavenCentral()) and changed the group id to "com.github.thejuki".

```
implementation "com.github.thejuki:k-form-master:8.2.1"
```

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
