### ISSUE TITLE
Support for ListItem

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#26]
## Description

According to the docs, drop down can use a list of ListItems and it should work, however I cannot seem to get it to work when I declare FormPickerDropDownElement<ListItem>.

Why is ListItem not included with the framework if its supported?

**Comment by TheJuki** [comment]
Perhaps I should add that to the Notice on that page. The ListItem, ContactItem, and ContactAutoCompleteAdapter classes are provided in the example app. Those classes are used for testing the example app. Feel free to include the class in your project. 

https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/item/ListItem.kt

**Comment by dhaksddj** [comment]
But how does it work? How does the framework know about the id and name fields in ListItem?

I did copy over the ListItem class but it didn't work, the options displayed as a toString() representation of ListItem.

**Comment by TheJuki** [comment]
The purpose of the ListItem class is to demonstrate how to make your own class.  All it worries about is that it implements Serializable and has a toString() method. The id and name are just variables of your own choice. Name is displayed because that is what the toString() method returned.

**Comment by TheJuki** [comment]
I updated the docs to explain the purpose of ListItem.
