### ISSUE TITLE
Not working with latest version of Dhaval2404/ImagePicker

### ISSUE THREAD

**Issue by VincentJoshuaET** [TheJuki/KFormMaster#281]
## Description

It seems that you are reusing this library with the same package names. I cannot use some methods from the standalone version of this library because either you removed it or your code isn't updated.

**Comment by TheJuki** [comment]
I just released [8.3.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this is fixed now.
