### ISSUE TITLE
Dealing with validation of free form text

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#29]
This is more a question looking for ideas. 

When I declare a FormMultiLIneEditTextElement, everytime the use enters a character, the listeners fire.

Is there some way to know when they have finished typing? Maybe some sort of out of focus listener which I could use to trigger validation?

**Comment by TheJuki** [comment]
I agree. Firing after every character is unnecessary. I am using a FocusChangeListener for FormTokenAutoCompleteView which works pretty well.

**Comment by dhaksddj** [comment]
How can I use that? It seems to be used in the ViewBinder classes rather than the Form elements.

**Comment by TheJuki** [comment]
I am planning to work on this for the next release.

**Comment by TheJuki** [comment]
I just released [4.1.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if updating the value when the form element loses focus works for you.

**Comment by dhaksddj** [comment]
I'm not sure what to do here. I have updated but not seeing any new methods to use.

Is there an example somewhere?

**Comment by dhaksddj** [comment]
Hi, so I worked out what you did. The listeners won't fire until you navigate away from the field.

Due to my custom requirements, this does not work for me. The reason is, I use the firing of the listener to enable the next element (which now won't appear) in addition, I disable previous elements once I move away from them. So essentially, all I can do is enter text into the field but no way to leave.

Maybe instead of using loss of focus, could the keyboard option Done or Next be used to fire the event? That would require the ability to set inputType (other issue I raised today).

In the meantime, I will experiment with showing the next field if the current field is a freetext field.

**Comment by dhaksddj** [comment]
Unfortunately, the latest version 4.1.0 no longer works for me for the reasons above.

Since there is no pre-display-of-element event, I can't check is the next element is a *EditTextElement to then enable the subsequent element (so you have somewhere to lose focus to).

I'm going to have to rollback to 4.0.1.

Sorry about this, you have been very helpful. If you choose to keep this latest change I may be forced to fork the project so I do not get the 4.1.0 change.

I'll investigate other options in the meantime.

**Comment by TheJuki** [comment]
I understand. Updating the value when focus is lost is not the best solution. I read an article that I could use RxJava to wait a few seconds before updating the value when the text changes. Perhaps I could try that out. https://medium.com/@elye.project/periodic-processing-of-text-change-in-edittext-2fd44a1ef2cd

**Comment by dhaksddj** [comment]
I think introducing the RxJava library just for this is overkill. Here's some [SO](https://stackoverflow.com/questions/8063439/android-edittext-finished-typing-event) answers that do something similar with platform classes.

Some solutions are also looking to utilize the keyboard. But then we need access to inputType.

**Comment by dhaksddj** [comment]
I think my only choice is to make a copy of the built in widgets and customise them by adding listeners.

I want to try this method https://developer.android.com/training/keyboard-input/style#Action.

Can you tell me what to copy so I can have my own version of FormMultiLineEditTextElement?

**Comment by TheJuki** [comment]
I just released [4.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this works for you. I restored addTextChangedListener to update value as characters are typed by default and added updateOnFocusChange to update on focus instead.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
