### ISSUE TITLE
Error in jitpack

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#292]
Hi there,

i can not download the latest 8.2.1 because of an error on jitpack.io
![C9502DCD-2918-44D0-8393-B5F6B014A291](https://user-images.githubusercontent.com/8148815/153412893-044a7eba-4fc8-4cd3-a0a0-86424f04436e.png)

**Comment by TheJuki** [comment]
I just released [8.3.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this works for you. I also pushed 8.2.1.1 as a tag for Jitpack which is 8.2.1 but can build in Jitpack.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
