### ISSUE TITLE
LabelRow inside the form

### ISSUE THREAD

**Issue by stvalentin** [TheJuki/KFormMaster#32]
I'm trying at this moment to create a complex form where most of the processing is happening on the server.

One way to show the errors of form elements it's to use a LabelRow (I already achieved this with Eureka form on iOs), but if you have something similar please let me know, otherwise I already started on implementing something similar (maybe I can add it to your project as a basic component)

**Comment by TheJuki** [comment]
The closest elements are the Text View and Header. I could added a Label where the title field takes up the entire row though.

**Comment by TheJuki** [comment]
I just released [4.1.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if updating the new label form element works for you. See Docs: https://thejuki.github.io/KFormMaster/element/label/

**Comment by stvalentin** [comment]
That is a very nice addition, thank you very much!
