### ISSUE TITLE
FormPasswordEditTextElement Field is always empty 

### ISSUE THREAD

**Issue by stvalentin** [TheJuki/KFormMaster#33]
I'm playing with the password field on finishing the register view

Just that the FormPasswordEditTextElement is always empty when I try to retrieve the field value.

when check if the form is valid:

```
formBuilder.elements.forEach({
                    if (!it.isValid) {
                        it.error = "This field is required!"
                    }
                })
```
It always shows that the field is empty

And the same thing I also get when I try to access the field manually via the line:
val passwordElementValue = formBuilder.getFormElement<FormPasswordEditTextElement>(Tag.Password.ordinal).value as String?
or 
When I'm checking it via the debugger.

Any tips on where to check this because I was looking at the code to submit a PR but I couldn't find anything so far

**Comment by TheJuki** [comment]
With the recent update those types of fields only update when they have lost focus. So, if the field is currently focused and you need to get the value clear the focus first:

```
currentFocus?.clearFocus()
```
