### ISSUE TITLE
Access to inputType

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#34]
Hi, is there some way to set this value without creating my own custom component?

**Comment by TheJuki** [comment]
Not currently. Are you looking the change the InputType of FormSingleLineEditTextElement?

**Comment by dhaksddj** [comment]
Maybe later but currently FormMultiLineEditTextElement because the default soft keyboard comes up with new line button, so when you have finished typing, you have to dismiss the keyboard (awkward) and then tap the next question to move on.

I would like to specify the inputType so that the Done or Next button appears instead. I expect them to not need new line for my app.

**Comment by TheJuki** [comment]
I just released [4.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this works for you. imeOptions is what you are looking for. See my updated example for textArea: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L210

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
