### ISSUE TITLE
Element is visible even though set to invisible

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#35]
## Description

[Description of the bug]

My form is meant to display questions one by one as a user answers them.

I accomplish this by building the form and its elements and setting visibility to false (line 153). Then I go through and explicitly enable the first question (line 182).

However, what I am seeing is that Question 3 (tag 3) is visible. The logcat output in the image shows Element with tag 3 is set INVISIBLE (visible = false).

Playing around, if i set tag 3 manually to invisible (line 183) it will disappear.
### Expected behavior

elements set to visible = false are not shown
### Actual behavior

an element set to visible = false is shown on the UI

### KFormMaster version

* Version: 4.0.1

### System information

* Android OS: 8.1/Latest
* Issue in Emulator: Yes/No/Untested
* Issue in physical device: Yes/No/Untested

**Comment by TheJuki** [comment]
BaseFormViewBinder should be handling this. What Form Element is it?

**Comment by dhaksddj** [comment]
FormPickerDropDownElement

**Comment by dhaksddj** [comment]
I've many instances of this though, so I don't know why I've only seen this now (I have multiple forms).

**Comment by dhaksddj** [comment]
I've been doing further investigation. If I create a form with 4 FormPickerDropDownElements, it all works fine.

When I replace one (the second one in my case) with a FormPickerDateElement, this issue occurs.

**Comment by TheJuki** [comment]
Replace? How are you doing that?

**Comment by dhaksddj** [comment]
Not at runtime! I mean I changed the form, changing the second element.

**Comment by TheJuki** [comment]
Okay. I will do some testing with that.

**Comment by dhaksddj** [comment]
You have a fix? Please be aware I am on 4.0.1 since 4.1.0 contains the focus changed amendment that won't work for me.

I would be grateful if you could back port the fix (4.0.2?)

**Comment by TheJuki** [comment]
I just released [4.2.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if this has been fixed.

**Comment by dhaksddj** [comment]
Like I said earlier, I am unable to use the latest version with the edittext focus listener change.

Do you mind back porting the fix to 4.0.1?

**Comment by TheJuki** [comment]
This release has both. It will use addTextChangedListener by default.

**Comment by dhaksddj** [comment]
Thanks! Will update and let you know if I have issues.

**Comment by dhaksddj** [comment]
Just upgraded and the issue is still there.

**Comment by dhaksddj** [comment]
I moved my code to use the builders (DropDownBuilder, DateBuilder, etc) and the bug has gone. Perhaps I should never have used the Form*Element classes?

**Comment by TheJuki** [comment]
Incredibly bizarre. I recommend using the Kotlin DSL since it uses the builders (That is how I tested this issue). Not sure why the builders work in your case.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
