### ISSUE TITLE
Form element set to visible = false still appears

### ISSUE THREAD

**Issue by dhaksddj** [TheJuki/KFormMaster#39]
Hi,

I know I mentioned this before but it has reappeared. I'm looping through the elements, setting them to false but one element still appears. Logcat shows it is being set to false.

Can you have a look because I'm struggling to find a workaround?

You mentioned last time using the dsl but not sure if that will make difference when I want to amend an existing form elements via FormBuilder class.

**Comment by TheJuki** [comment]
When you are logging the elements can you also check if itemView is null or not? Are you looping through the elements after the form has been rendered and displayed or before? My only guess is that itemView is null and cannot be set visibility = View.GONE for that element. Which kind of form element is it?

**Comment by dhaksddj** [comment]
Its a FormMultiLioneEditTextElement.

I am looping through after being displayed.

ItemView is NOT null and I can loop through the code that sets visibility to GONE (BaseFormElement line 239).

**Comment by TheJuki** [comment]
I think it might be the cache size then. Are you using addFormElements() to add form elements? If not, you should call setItems() after you modify the elements list. This will make sure the cache size is correct and notifyDataSetChanged is called.

**Comment by dhaksddj** [comment]
So I call FormBuilder with just the activity (it used to have automeasure but thats gone) like this:

```
formBuilder = FormBuildHelper(activity!!)
formBuilder.attachRecyclerView(activity!!, recyclerView)
```

then I loop through my questions, creating elements as I go and then add them:
```
formBuilder.addFormElements(elements)
```

Apart from the first question, I make all of them visible = false. Then, as they answer questions I can check the answer and decide which elements to make visible.

The issue is changes to previously answered questions need questions after it to be made invisible again (because answering questions differently might mean making other questions visible).

So, based on your comment I tried this:
```
when (formElement) {
                is FormPickerDropDownElement -> formElement.setVisible(false)
                is FormMultiLineEditTextElement -> {
                    formElement.setVisible(false)
                }
            }
            formBuilder.setItems()
```

that made no difference.  Any ideas?

**Comment by TheJuki** [comment]
Could it be that the field has focus? https://stackoverflow.com/a/28467157/4056401

Call currentFocus?.clearFocus() before your loop to hide the elements.

**Comment by dhaksddj** [comment]
On what class?

**Comment by dhaksddj** [comment]
```
when (formElement) {
                is FormPickerDropDownElement -> {
                    formElement.editView?.clearFocus()
                    formElement.setVisible(false)}
                is FormMultiLineEditTextElement -> {
                    formElement.editView?.clearFocus()
                    formElement.setVisible(false)
                }
            }
```

didn't work (also tried itemView which returns a view)

**Comment by TheJuki** [comment]
Hmm. I really don't know. Seems like an Android problem. Caching the RecylerView should resolved most of the weirdness for each dynamic view in the list.

**Comment by dhaksddj** [comment]
Caching is the default anyway?

**Comment by TheJuki** [comment]
Yes. But apparently it does not solve all of the issues with using a RecylerView for a form.
