### ISSUE TITLE
Question about AppCompatActivity

### ISSUE THREAD

**Issue by josmas** [TheJuki/KFormMaster#40]
## Description

This may not be a bug as such, but I tried to integrate the library a couple of times in an existing project and couldn't make it work (until now!) so just wanted to ask if this is a known issue, or is it documented somewhere that I did not check or see?

The issues is the following: I can see the list of form elements, but only the labels (no checkboxes or any other elements) and I cannot click or edit anything.

It turns out that when I switch from Activity to AppCompatActivity, all starts working normally. This does not happen with Fragments, I do not need to use the v4 compat version of that class, it works fine with a normal Fragment, but it does happen with Activity.

### Expected behavior

I would expect this to either work with an Activity class, or be documented somewhere (which may already be, but I have not found where).

### Actual behavior

As explained earlier, when creating a form in an Activity, only the labels appear, and elements are not clickable, or editable or anything.

### Steps to reproduce the bug

Follow the getting started guide but use and Activity instead of an AppCompatActivity class.

### KFormMaster version

* Version: tested with 4.5.0 and 4.5.1
### System information

* Android OS: 8.1
* Issue in Emulator: Yes
* Issue in physical device: Untested

**Comment by TheJuki** [comment]
It may be because every element is using the AppCompat version. 

https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/widget/ClearableEditText.kt 

This is a custom widget I created to display an X for clearable elements. Perhaps it should extend EditText instead. I am not sure if there would be any difference between the two.

**Comment by josmas** [comment]
Thanks for the info!

Have you made any changes in 5.0.0? It seems to work with an Activity now. The only difference I've noticed so far is that _button_ elements seem to lose style properties (instead of centred and in capitals, they appear on the right and in lower case when using an Activity).

It's not a big deal, but thought I'd ask.

**Comment by TheJuki** [comment]
Yeah I noticed that too. Not really sure why. But AppCompatActivity seems to keep everything happy.
