### ISSUE TITLE
Type Radio as Button Group

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#41]
Hi there,

I'm looking for a way to create a button group which is acting like a custom radio button. So it could by something like a SwitchFormType with more than two switches.

You can find an example attached.

![example](https://user-images.githubusercontent.com/8148815/44268570-2bb2c200-a232-11e8-9e4d-3a0e6c41c6df.jpg)

**Comment by TheJuki** [comment]
I could try implementing this library: 
https://github.com/Kaopiz/android-segmented-control
or this one:
https://github.com/RobertApikyan/SegmentedControl

**Comment by darkwood-studios** [comment]
I think this one could do the trick: https://github.com/Kaopiz/android-segmented-control

Or maybe an even better source without an library -> https://medium.com/@staceypyee/revealing-the-magic-of-creating-ios-segmented-control-with-image-in-android-kotlin-part-1-7d817f9d5c7

**Comment by TheJuki** [comment]
I just released [4.6.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the Segmented element works for you. Check out the docs: https://thejuki.github.io/KFormMaster/element/segmented/

**Comment by darkwood-studios** [comment]
Hi @TheJuki 

looks really great! One question left:

I want to customize colors, spacings and sizes. So my idea was to create a custom layout as you explained here : https://github.com/StarkSoftware/SSForms/issues/3

I copied the form_element_segment.xml into my project and changed some values - but unfortunately nothing changes in the app. Do you have any idea why that does not work?

Thanks for your great support.

**Comment by TheJuki** [comment]
I copied and converted the main class from https://github.com/Kaopiz/android-segmented-control 
 
Here: https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/widget/SegmentedGroup.kt

It controls most of styling. I can add new properties to the FormSegmentedElement class which can talk to and update the SegmentedGroup class.

As for the title, I can check if the title is null or empty and make the View be View.GONE.

**Comment by darkwood-studios** [comment]
> As for the title, I can check if the title is null or empty and make the View be View.GONE.

That would be perfect.

> It controls most of styling. I can add new properties to the FormSegmentedElement class which can talk to and update the SegmentedGroup class.

Ah I see. So I can set colors and corner with that class. But what I'm missing is to set the layout to fill horizontal. Perhaps you have an idea to implement this.

Thats now:

![before](https://user-images.githubusercontent.com/8148815/44784150-efb22200-ab8c-11e8-8399-5c1270deb6e4.png)

So it should look like:

![after](https://user-images.githubusercontent.com/8148815/44784152-f17be580-ab8c-11e8-90bd-690986801222.png)

**Comment by TheJuki** [comment]
Oh. Hmm. I'll play around with it but it should be possible. Again, I'll make this a property in FormSegmentedElement.

**Comment by darkwood-studios** [comment]
> So, I'll add "fillSpace" as a property.

Sound perfect. Thank you.

Maybe you could add some properties for colors, corner and margin/padding as well.

I may be able to change color by adding "colorFormMasterElementRadioSelected" in my colors, but changing the corner radius by adding R.dimen.elementRadioCornerRadius to my dimens.xml is not working. Maybe a property could handle that.

And some properties to change text size and button padding would add more flexibility, too. What do you think?

**Comment by TheJuki** [comment]
Sounds good!

**Comment by TheJuki** [comment]
![](https://user-images.githubusercontent.com/2180227/44811447-568a0800-ab9a-11e8-9cfe-d6229f78b9eb.PNG)

Making progress...

**Comment by TheJuki** [comment]
I just released [4.6.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new properties works for you. The title for segmented will also be View.GONE if null or empty.

**Comment by darkwood-studios** [comment]
So I close this issue now. You did a great job on this feature.
