### ISSUE TITLE
Steps in Slider not working

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#43]
## Description

The slider ignores the declared steps

### Expected behavior

If I declare steps = 50 I expect, that the slider snaps in 50-steps... ex. 0, 50, 100, ..., 500, 550, 600, ...

An value of 49 or 113 should not be possible.

### Actual behavior

The slider does not snap to any divisor of 50. A value of 49 or 113 can be selected.

### Steps to reproduce the bug

1. create slider
 slider(1) {
                steps = 50
                min = 100
                max = 1000
}

2. slide the slider to any position
3. = no divisor of 50 selected

### KFormMaster version

* Version: Latest

### System information
* Pixel 2 XL
* Android OS: 8.1
* Issue in Emulator: Yes
* Issue in physical device: Untested

**Comment by TheJuki** [comment]
https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L373

Yeah steps are not the greatest... Right now, if you set steps to 20, then it will have 20 ticks. This means that from 0 to 100 it will go in 5s: 0, 5, 10, 15,...,100.

**Comment by TheJuki** [comment]
So, in your case you would use 18 steps. If that is too confusing I can change it or use another metric.

**Comment by darkwood-studios** [comment]
Ah i understand. I think the solution that I described is more flexible. In my app I will have a very big range for the slider. from 1.000 -> 1.000.000 - and I will have a tick every 500. so I've expected that I could define step = 500 to archive that.

With you logic I probably should set steps to 2.000 to archive 500 steps to one million... maybe the first approach is more intuitive.

**Comment by TheJuki** [comment]
I just released [4.6.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new incrementBy property works for you.

**Comment by darkwood-studios** [comment]
works great. thank you!
