### ISSUE TITLE
Change Slider value on sliding

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#44]
Hi there,

it's really hart for the user to hit the value he wants, when it's not shown. 

I think the slider should update its visible value while sliding, so that the user can stop sliding when he reaches the value he wants.

**Comment by TheJuki** [comment]
I just released [4.7.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the updated slider element works for you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
