### ISSUE TITLE
How do remove divider from Form-Items

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#45]
Hi there,

I want to remove the divider from my form items. Usally I use the following code to remove the lines from the recycler view.

`recyclerView?.addItemDecoration(DividerItemDecoration(context, 0))`

But in combination with the forms it does'nt work. Maybe the formbuilder places its own ItemDecoration?

**Comment by TheJuki** [comment]
I just released [4.7.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if displayDivider works for you. Check out the docs: https://thejuki.github.io/KFormMaster/element/base/#display-divider

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
