### ISSUE TITLE
Max length for Number input

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#46]
Hi there,

I want to use the NumberFormField for zip code input. The zip could have maximum 5 digits. Is it possible to set a max value for number felds?

**Comment by TheJuki** [comment]
I just released [4.7.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if maxLength works for you. Check out the docs: https://thejuki.github.io/KFormMaster/element/base/#max-length

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
