### ISSUE TITLE
When form has many fields, the values is switched / replaced after scroll

### ISSUE THREAD

**Issue by khalifavi** [TheJuki/KFormMaster#5]
this might be caused by some adapter implementation, will also look into the source code

**Comment by TheJuki** [comment]
Which version are you using? The library I am using had that issue before I added View States.

**Comment by khalifavi** [comment]
I'm using 2.1.0
Found that when we call `setItemViewCacheSize(Tag.values().size)` to RecyclerView helped

**Comment by TheJuki** [comment]
https://android.jlelse.eu/anatomy-of-recyclerview-part-1-a-search-for-a-viewholder-404ba3453714

I found this article so that I can understand how the RecyclerView cache works. Would you suggest that I set the cache size after the form elements are added?

**Comment by khalifavi** [comment]
For a reasonable form field size (say 20 or 30) it would be fine though, but 100 fields could eat a lot of memory & defeats purpose of "recycling views" recyclerview.

IMO, it's OK, since this library is for Form making, not really about list / recycling view.

I mean, it will be a great workaround

**Comment by TheJuki** [comment]
I have added cacheForm to the FormBuildHelper class in version 2.1.1. You can set it in the constructor. By default it is false. Let me know if it works the same way you are using setItemViewCacheSize(Tag.values().size).

**Comment by khalifavi** [comment]
That will do, Thanks 👍
