### ISSUE TITLE
Change of background and text color not working

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#50]
## Description

backgroundColor and valueTextColor not working

### Expected behavior

backgroundColor = COLOR should change the color of the field to the given one
valueTextColor = COLOR should change input value color to the given one

### Actual behavior
backgroundColor = COLOR changes the background to a dirty purple instead of the given one
valueTextColor = COLOR does nothing

### Steps to reproduce the bug
Code for form builder
```
 number(FormField.ZIP) {
                title = "Postleitzahl"
                required = true
                value = "81245"
                numbersOnly = true
                clearable = true
                valueObservers.add { newValue, element ->
                    if(newValue?.length == 5) {
                        zipCode = newValue
                        loadOfflineData()
                    }
                }
            }
```

Code for changing the color:
```
formBuilder.getFormElement<FormNumberEditTextElement>(FormField.ZIP).backgroundColor = R.color.offlineDataGreenLight
            formBuilder.getFormElement<FormNumberEditTextElement>(FormField.ZIP).valueTextColor = R.color.offlineDataGreen
            formBuilder.getFormElement<FormNumberEditTextElement>(FormField.ZIP).titleTextColor = R.color.offlineDataGreen
```

Color-Ressource
```
<color name="offlineDataGreen">#5cb85c</color>
<color name="offlineDataGreenLight">#eef8ee</color>
```

### KFormMaster version

* Version: 4.7.0

### System information

* Android OS: 8.1/Latest
* Issue in Emulator: Yes
* Issue in physical device: Untested

**Comment by TheJuki** [comment]
I will need to update my docs to clarify. You will need to get the Color Int: https://stackoverflow.com/a/5271452/4056401

```
ResourcesCompat.getColor(getResources(), R.color.your_color, null); // without theme
ResourcesCompat.getColor(getResources(), R.color.your_color, your_theme); // with theme
```

**Comment by TheJuki** [comment]
The docs have been updated: https://thejuki.github.io/KFormMaster/element/base/

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
