### ISSUE TITLE
Validation and Error examples

### ISSUE THREAD

**Issue by josmas** [TheJuki/KFormMaster#52]
## Description

Not a bug as such, I believe I am just not using it correctly.
### Expected behavior
If I have an element and a button like:
```
      text {
        title = getString(R.string.city)
        hint = "city"
        required
        maxLength = 2
      }
      button {
        value = "Submit"
        valueObservers.add { _, _ ->
          if (formBuilder.getElementAtIndex(0).isValid) {
            toast("form is valid!")
          }
          else {
            toast("form is not valid!")
          }
        }
      }
```
I would expect that the form is not valid if I type nothing in the text field. But it always goes through.
`formBuilder.isValidForm` seems to also be always true.

With errors, when I have an element like this:
```
      text {
        title = getString(R.string.city)
        hint = "city"
        error= "This is the error message"
        required
        maxLength = 2
      }
```
I see the error message in red when the form loads, but after that, even if the field is changed and then emptied again, the error message goes away and never comes back.

So I believe I am doing something wrong, or not understanding how this works. I have tried using the values inside and outside of observers, but can't get any proper validation working.

Any help would be greatly appreciated.

### KFormMaster version

* Version: 5.0.0

### System information

* Android OS: 8.1 on emulator
* Issue in Emulator: Yes
* Issue in physical device: Untested

**Comment by TheJuki** [comment]
Unfortunately, you have handle validation yourself. So, you'll need to determine if each element is valid or not and set the error if it is not. The error value is set to null when the element is changed.

See https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L114

**Comment by TheJuki** [comment]
Also, see this:
https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/model/BaseFormElement.kt#L450

It should detect if the element value is null or empty. But if it is not then you can add a check yourself before setting the error.

**Comment by josmas** [comment]
Hey @TheJuki thanks for the pointers. It was me being silly, as usual...

If you look at the code above I have:
```
  text {
    required
  }
```
Instead of:
```
  text {
    required = true
  }
```

For some reason I thought it would override the default `false` value. So that is why it is always going through.
Nice to have the pointers to code anyway! :)
I'll close this now.
