### ISSUE TITLE
ListItem and ContactItem classes

### ISSUE THREAD

**Issue by josmas** [TheJuki/KFormMaster#53]
## Description

ListItem.tk and ContactItem.tk are only defined in the examples package and one test folder, but they are used in the docs. If one only adds the library as a dependency, none of the two classes are available.

### Expected behavior

If I copy a snippet from the docs, I expect it to work.

### Actual behaviour

The classes cannot be found. I've copied them to my project's src and that solves the issue, but it seems odd to have to do that. If they are core, they should be in the core library, if not, maybe use some alternative examples?
I don't know what the right thing to do is here, but at a minimum, indicate in the docs that this will happen. ListItem is used in several places in the docs, but unless I am missing it, I don't see any indications of this.

### Steps to reproduce the bug

1. Start a fresh project with the library as a dependency
2. Copy dropdown examples from the docs as:
```
  dropDown<ListItem>(1) {
      dialogTitle = "Select One"
      options = listOf(ListItem(id = 1, name = "Banana"), 
                       ListItem(id = 2, name = "Orange"))
      value = ListItem(id = 1, name = "Banana")
  }
```
3. Figure out what to do with the imports that do not resolve.

### KFormMaster version

* Version: 5.0.0

### System information

* Android OS: 8.1
* Issue in Emulator: Yes
* Issue in physical device: Untested

Thanks!

**Comment by TheJuki** [comment]
> The ListItem, ContactItem, and ContactAutoCompleteAdapter classes are provided in the example app. Your custom class just needs to override toString() to display in the dialog.

https://thejuki.github.io/KFormMaster/element/dropDown/

This is explained in the docs where they are used as examples. You should not need these classes as you probably have classes of your own you want to use in a dropdown.
