### ISSUE TITLE
DropDownBuilder see the preselected value

### ISSUE THREAD

**Issue by ZuzanaBenicko** [TheJuki/KFormMaster#55]
Hello,

I would like to ask if there is possible to show the preselected value of DropDownBuilder with tick or something, to know what was chosen before opening DropDownBuilder. (Of course, if there was no chosen value before there is no need to show any tick).

![screenshot_1538225761](https://user-images.githubusercontent.com/9416708/46246057-313a2500-c3f8-11e8-9cfb-4049e26ee94b.png)

Thank you very much!

**Comment by TheJuki** [comment]
I just released [5.0.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new [displayradiobuttons](https://thejuki.github.io/KFormMaster/element/dropDown/#displayradiobuttons) property works for you. Enable it to show the normal radio buttons in the alert dialog that is displayed.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
