### ISSUE TITLE
Reduce margin/padding between fields

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#57]
Hi there,

I have to reopen the issue https://github.com/TheJuki/KFormMaster/issues/51

There are two problems with the layout solution
1.) I have to remove the title part, too, if I want to reduce the gap to a minimum. This should be more flexible. I should be possible to remove/hide the title/label for each input
2.) Similar problem with the padding. I want to reduce the paddingBottom to 0dp - but only for one single form element and not for all of this type.

I suggest two new options for the form element.

layoutPaddingBottom = 0 // the padding bottom of the LinearLayout
hideTitle = true // if true, the LinearLayout of the formElementTitle will be removed

**Comment by TheJuki** [comment]
I just released [5.0.2](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency. I added [layoutPaddingBottom](https://thejuki.github.io/KFormMaster/element/base/#layout-padding-bottom-dp), [displayTitle](https://thejuki.github.io/KFormMaster/element/base/#display-title), and [margins](https://thejuki.github.io/KFormMaster/element/base/#margins-dp) to the base form element.

**Comment by darkwood-studios** [comment]
I can not test the new version. Please see: https://github.com/TheJuki/KFormMaster/issues/59

**Comment by darkwood-studios** [comment]
Works. Thx!
