### ISSUE TITLE
SegmentedListItem: Drawable should fit size

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#61]
Hi there,

the SegmentedListItem with a drawable works great so for. But if I set the name to null there is a huge space left below the icon. 

Better:
If there is no name set for the button, the drawable should use the additional space and scale to fit.

![icons2](https://user-images.githubusercontent.com/8148815/46998481-f1c34680-d122-11e8-82a2-641d773b504a.png)

**Comment by darkwood-studios** [comment]
Thanks for that. I see one problem here:

If I use >> FormSegmentedElement.DrawableDirection.Center << the title disappears even if it's set. If a title is available (not null) it should be visible in the button.

**Comment by TheJuki** [comment]
I mean that is what the other directions are for. Top and Bottom will display the title.

**Comment by darkwood-studios** [comment]
ok I see. My problem is, that I have to choose the direction for the form element (segmented) and have no chance to assign it to the list items.

My usecase:

I have one segmented form element which could hold two different lists in its options.

List one is a list of drawables with a title.
List two is a list of drawables without title.

I expected that I could set the direction for each ListItem and not for the element itself.

Does it make sense? Or should I change the direction of the element at the place where I change the options?

**Comment by TheJuki** [comment]
https://github.com/TheJuki/KFormMaster/tree/multiple_drawable_directions

It behaves oddly when using multiple directions. I created a branch which allows this. Not entirely sure how to fix the height issue.
<img width="342" alt="screen shot 2018-11-04 at 3 13 25 pm" src="https://user-images.githubusercontent.com/2180227/47969973-dcb44600-e044-11e8-8f56-dd77a3e6f313.png">
<img width="343" alt="screen shot 2018-11-04 at 3 14 17 pm" src="https://user-images.githubusercontent.com/2180227/47969974-dcb44600-e044-11e8-83ab-a56a7dda66ee.png">

**Comment by darkwood-studios** [comment]
For me it's fine with the difference in height, because i will change all of the items. So I will have a segmented list with text - or a complete segmented list without text. (I change the complete option list dynamically for the segmented form element)

**Comment by TheJuki** [comment]
I just released [6.5.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if using radioGroupWrapContent, radioButtonWidth, and radioButtonHeight  work for you. See: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/FullscreenFormActivity.kt#L594

You can also set the direction for each button now. 
See: https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/widget/SegmentedDrawable.kt#L19

See: https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/item/SegmentedListItem.kt#L18

**Comment by darkwood-studios** [comment]
Hi @TheJuki 

thanks for you update. I have some questions regarding the radioButtonHeight.

1. What height is correct?
I use a drawable with a height of 32dp (no title) and a margin of 16 for top and bottom. So I expect a total height of 64. But if I set radioButtonHeight = 64 the button is way to small.

2. How to change the height dynamically?
I want to change the height of the button if it has no title. But it's not working correctly. (sometimes it changes the height, and sometimes not) Maybe I'm doing something wrong

Here is my example:

```
segmented<SquareMeterListItem>() {
                options = squareMeterList
                value = squareMeterList[1]
                rightToLeft = false
                fillSpace = true
                displayDivider = false
                radioButtonHeight = value?.getHeight()
                margins = FormElementMargins(16, 0, 16, 0)
                valueObservers.add { newValue, _ ->
                    radioButtonHeight = newValue?.getHeight()
                }
            }

data class SquareMeterListItem(val id: Long? = null, val name: String? = null, val usage: String? = "", @DrawableRes override var drawableRes: Int? = 0) : SegmentedDrawable {
    override fun toString(): String {
        return name.orEmpty()
    }

    /**
     * Return the height of the radio button
     * @return Int?
     */
    fun getHeight(): Int? {
        if(name == null) {
            return 64
        }

        return 128
    }
}
```

radioButtonHeight = value?.getHeight()

**Comment by TheJuki** [comment]
I just released [6.5.1](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency. 

Fixed FormSegmentedElement radioButtonWidth and radioButtonHeight to use dp.
Made FormSegmentedElement properties dynamic. 
Added height and width to SegmentedDrawable. Override them in SquareMeterListItem to set the width and height for each radio button.

**Comment by darkwood-studios** [comment]
Great one. Works! Thank you for the update. :-)

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
