### ISSUE TITLE
dropDown triggers not the valueChangedListener

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#63]
Hi there,

im using the OnFormElementValueChangedListener to trigger a save operation if any value of a field changes. With text fields this works very well, but if I change the value of a dropDown the listener is ignored.

I think the value change of a dropDown should trigger the OnFormElementValueChangedListener as well.

**Comment by TheJuki** [comment]
I just released [5.0.7](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if valueChangedListener is working for the dropdown element.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
