### ISSUE TITLE
Segmented control value not getting triggered

### ISSUE THREAD

**Issue by TwunTee** [TheJuki/KFormMaster#64]
## Description

Segmented Control value observer nor the value of the segmented control is not getting triggered when clicked for the first time(empty form), any further clicks on the value selected first also doesn't seem to trigger the value change, it works properly if i set a initial value though.

### Expected behaviour

The value should change when selection a segment for the first time even though the segment element initial value is null

### Actual behaviour
The value of the segmented control is not getting triggered when clicked for the first time.

### Steps to reproduce the bug

1. Setup a segmented control without any initial value
2. Add value observer
3. Click on any segment, the value wont be changed even though a button has been clicked

### KFormMaster version

Version: Latest

**Comment by TwunTee** [comment]
Sorry everything works fine except the UI is not getting updated when the value is set runtime even though the underlying value is updated. That gave me the impression the value wasn't getting updated.

**Comment by TheJuki** [comment]
I just released [5.0.7](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if Segmented element is working now.

**Comment by TwunTee** [comment]
Thank you will check it out!

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
