### ISSUE TITLE
Text align for text views

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#66]
Hi there,

I'm missing a param to change the alignment/gravity of the text view. I want to center the text within the view. Is there a way to to that?

Best regards,
Daniel

**Comment by TheJuki** [comment]
I just released [5.0.7](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new [centerText](https://thejuki.github.io/KFormMaster/element/base/#center-text)  property works.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
