### ISSUE TITLE
how to create a custom from element?

### ISSUE THREAD

**Issue by blusewang** [TheJuki/KFormMaster#7]
how?

**Comment by TheJuki** [comment]
I will need to modify the code to allow this. Essentially you will need a new layout XML file, model class, and view class.

I will need add a new function to FormBuildHelper to allow you to register your new view:

```
fun registerCustomView(context: Context, view: CustomViewBinder)
    {
        this.formAdapter.registerRenderer(CustomViewBinder(context, this).viewBinder)
    } 
```

**Comment by TheJuki** [comment]
Update your build.gradle dependency with version 2.2.2. You can now add custom form elements! See the new example in this repo to see how.

https://github.com/TheJuki/KFormMaster/tree/master/app/src/main/java/com/thejuki/kformmasterexample/custom

https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/java/com/thejuki/kformmasterexample/CustomFormActivity.kt

**Comment by blusewang** [comment]
WOW!

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to re-open!
