### ISSUE TITLE
Show header in collapsed state on startup

### ISSUE THREAD

**Issue by thuijssoon** [TheJuki/KFormMaster#72]
Hi there,

Thanks for an awesome library and continuous development! Is it possible to set a header state to collapsed on start up? I have tried `setAllCollapsed(true)`, but this appears not to be working for me. This code I use at the moment is:

``` 
HeaderBuilder headerBuilder = new HeaderBuilder(getString(R.string.some_text));
headerBuilder.setCollapsible(true);
FormHeader fh = headerBuilder.build();
fh.setAllCollapsed(true);
elements.add(fh);

//... Some more elements ...

mFormBuilder.addFormElements(elements);
```

Am I missing something?

**Comment by TheJuki** [comment]
I believe setAllCollapsed only works after the Form is rendered. I'll need to make adjustments to the code.

**Comment by TheJuki** [comment]
The Form Header can collapse elements later by calling [setAllCollapsed](https://thejuki.github.io/KFormMaster/element/header/#set-all-collapsed-later).

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
