### ISSUE TITLE
image picker with Drawable 

### ISSUE THREAD

**Issue by faizan321** [TheJuki/KFormMaster#75]
How can i add the image view in form? like if i want to pick the image from camera and gallery and show in form?

**Comment by faizan321** [comment]
How can i add the image view in form? like if i want to pick the image from camera and gallery and show in form?

**Comment by TheJuki** [comment]
https://github.com/TheJuki/MaterialFileChooser

I will need to fix up this fork but I did get this to work with KFormMaster.

**Comment by darkwood-studios** [comment]
Maybe this request could work well with this one: https://github.com/TheJuki/KFormMaster/issues/87

**Comment by soareseneves** [comment]
Maybe this will help: #119 It is already merged and awaiting TheJuki to update docs/examples/version

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
