### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#76]
Hi there, 

I've seen that there is a branch with the name "androidx" - is there any official way to use the branch?

I'm using android x, and have to create my own layouts of some FormElements, because they are not using androidx per default. What is the best practise to use this?

**Comment by TheJuki** [comment]
I just released [6.1.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the AndroidX upgrade works for you. I was holding off until RendererRecyclerViewAdapter released 2.7.0 to the main release channel. But the snapshot version that I helped upgrade to AndroidX is stable enough.

**Comment by darkwood-studios** [comment]
I changed dependency from 6.0.0 to 6.1.0 and got the following error:

>>>
Failed to resolve: com.github.vivchar:RendererRecyclerViewAdapter:2.7.0-SNAPSHOT
<<<

any idea?

**Comment by TheJuki** [comment]
Great...
Add the snapshots repo:

https://github.com/TheJuki/KFormMaster/blob/master/build.gradle#L27

```
repositories {
       maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by darkwood-studios** [comment]
works.

**Comment by TheJuki** [comment]
Closing this issue. I'll add this to the README.
