### ISSUE TITLE
Having problems with isValidForm method

### ISSUE THREAD

**Issue by Fuhrmann** [TheJuki/KFormMaster#8]
First, thanks for this amazing library!

This is my form with 3 simple dropdowns:

```
val formBuilder = form(context!!, formGeralRecyclerView) {
    dropDown<TipoVisita>(Tag.TipoVisita.ordinal) {
        title = getString(R.string.formace_field_tipovisita)
        options = viewModel.tiposVisitas.toList()
        required = true
        hint = getString(R.string.form_selecione)
    }
    dropDown<Atividade>(Tag.Atividade.ordinal) {
        title = getString(R.string.formace_field_atividade)
        options = viewModel.atividades.toList()
        required = true
        hint = getString(R.string.form_selecione)
    }
    dropDown<Area>(Tag.Area.ordinal) {
        title = getString(R.string.formace_field_area)
        options = viewModel.areas.toList()
        required = true
        hint = getString(R.string.form_selecione)
    }
}
```

As you noticed, I set required in all of them. Right after the initialization, I tried to validate the form, and I get that the form, even with no values selected, is valid as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/1160365/38877157-10b8472e-422c-11e8-92f3-7a97c8d661e5.png)

I debugged the `FormBuildHelper.isValidForm`  method and in this piece of code:

`!it!!.isHeader and it.isRequired() and (it.value != null)`

it returns false for all elements. Maybe I forgot to specifiy something in the field declaration or this is as designed? Shouldn't the `isValidForm` return false in this case?

The `none` function as documentation says:

`Returns `true` if no elements match the given [predicate].`

Since there are no elements matching the given condition (is not header, is required and *the value is not null*) the isValidForm returns true, meaning that my form is valid, but it is not.

If I set a predefined value in one of my dropdowns:

![image](https://user-images.githubusercontent.com/1160365/38877685-33df0052-422d-11e8-8756-6a3ed079be5e.png)

```
dropDown<TipoVisita>(Tag.TipoVisita.ordinal) {
    title = getString(R.string.formace_field_tipovisita)
    options = viewModel.tiposVisitas.toList()
    required = true
    hint = getString(R.string.form_selecione)
   **value = viewModel.tiposVisitas.toList()[0]**
}
```

The `isValidForm` returns false:

![image](https://user-images.githubusercontent.com/1160365/38877723-55dfeef0-422d-11e8-9f25-7ae152d637d5.png)

**Comment by Fuhrmann** [comment]
Ok, I guess this is FormMaster bug: https://github.com/adib2149/FormMaster/issues/10

**Comment by TheJuki** [comment]
When I converted FormBuildHelper to Kotlin it created that isValidForm with "none". It should be "all". I'll need to test this later to today and release a new version but I believe this should work and add validation for empty text elements as well.

I believe this should work:

  ```
  val isValidForm: Boolean
        get() {
            return (0 until this.formAdapter.itemCount)
                    .map { this.getElementAtIndex(it) }
                    .all { !it!!.isHeader && it.isRequired() && it.value != null && 
                            (it.value !is String || !(it.value as? String).isNullOrEmpty()) }
        }
```

**Comment by TheJuki** [comment]
Actually, this may work.

```
val isValidForm: Boolean
        get() {
            return (0 until this.formAdapter.itemCount)
                    .map { this.getElementAtIndex(it) }
                    .all {
                        (it!!.isHeader || !it.isRequired()) || (it.isRequired() && it.value != null &&
                                (it.value !is String || !(it.value as? String).isNullOrEmpty()))
                    }
        }
```

**Comment by Fuhrmann** [comment]
Thanks! I'll wait for the new release!

**Comment by TheJuki** [comment]
This should be fixed in version 2.1.3. Please update your dependency and let me know if you have any problems.

**Comment by Fuhrmann** [comment]
Its working now in 2.1.3 version. Thanks!

**Comment by TheJuki** [comment]
Great! I am closing this issue.
