### ISSUE TITLE
How to clean up observers

### ISSUE THREAD

**Issue by TwunTee** [TheJuki/KFormMaster#86]
Is there a way to clean up the observers when activity is finishing. I tried using formbuilder clear all but leak canary still says the form builder is being leaked. 

It would be great if form builder has a method to clean the observers of all the fields instead of looping through them manually

**Comment by TheJuki** [comment]
Can you copy/screenshot your leak canary report? EditText listeners may be something else.

**Comment by TwunTee** [comment]
Sorry for the delay in replying, been held up with other work. Making a barebones app to see if leak canary still reports. Will post the reports soon.

**Comment by TwunTee** [comment]
Tried making a new project, leak canary wasn't throwing up any errors. I fixed another leak in my original project and leak canary stopped throwing up warning when using the observers too. I disabled instant run also. Either of those where the real reason. Thanks for helping out.
