### ISSUE TITLE
How to get value from Check Box Element? 

### ISSUE THREAD

**Issue by chadbrochill317** [TheJuki/KFormMaster#89]

**Comment by TheJuki** [comment]
```
var formBuilder: FormBuildHelper = FormBuildHelper(this, recyclerView = kotlinx.android.synthetic.main.activity_my_form.recyclerView)

val elements: MutableList<BaseFormElement<*>> = mutableListOf()

val checkboxElement = FormCheckBoxElement<Boolean>(1).apply {
    title = getString(R.string.CheckBox)
    value = true
    checkedValue = true
    unCheckedValue = false
}

elements.add(checkBoxElement)

formBuilder.addFormElements(elements)
```

Later...
```
val checkBoxValue = formBuilder.getFormElement<FormCheckBoxElement>(1).value
```

That is one way to do it.

**Comment by chadbrochill317** [comment]
button(ButtonElement.ordinal) {
                value = "Sign Up"
                displayDivider = false
                enabled = true
                valueObservers.add { newValue, element ->
                    val confirmAlert = AlertDialog.Builder(this@SignupFormActivity).create()
                    confirmAlert.setTitle("Confirm to Signup")
                    confirmAlert.setButton(AlertDialog.BUTTON_POSITIVE, this@SignupFormActivity.getString(android.R.string.ok)) { _, _ ->

                        val signupTermsValue = formBuilder.getFormElement<FormCheckBoxElement>(TermsCheckBox.ordinal).absoluteValue
                        val signupPrivacyValue = formBuilder.getFormElement<FormCheckBoxElement>(PrivacyCheckBox.ordinal)

I am doing it that way, like from the full page example. So I am not sure where to place the (1) position? Sorry for all the questions.

**Comment by TheJuki** [comment]
```
val signupTermsValue = formBuilder.getFormElement<FormCheckBoxElement>(TermsCheckBox.ordinal).value

val signupPrivacyValue = formBuilder.getFormElement<FormCheckBoxElement>(PrivacyCheckBox.ordinal).value
```

**Comment by chadbrochill317** [comment]
Yeah still getting this error for it...

one type argument expected for class FormCheckBoxElement<T>

**Comment by TheJuki** [comment]
```
val signupTermsValue = formBuilder.getFormElement<FormCheckBoxElement<Boolean>>(TermsCheckBox.ordinal).value

val signupPrivacyValue = formBuilder.getFormElement<FormCheckBoxElement<Boolean>>(PrivacyCheckBox.ordinal).value
```

**Comment by chadbrochill317** [comment]
Thank you, you are a god!
