### ISSUE TITLE
Custom validation for any element

### ISSUE THREAD

**Issue by rdsarna** [TheJuki/KFormMaster#95]
Hi, to enhance customisability, a validation function can be added as a public property to the BaseFormElement which is then called by the getter of `isValid` property. This way, any client can pass custom validation code while instantiating the element.

For example, 
```
formBuilder = form(this, recyclerView) {
            email(1) {
                title = "Email Address"
                validityCheck = {
                    value?.matches("some regex".toRegex()) == true
                }
            }
        }
```

This is how I've tried to accomplish the above enhancement in `BaseFormElement` -
```
    /**
     * Base validation
     */
    open val isValid: Boolean
        get() = validityCheck()

    /**
     * Form element custom validity check
     */
    open var validityCheck: () -> Boolean = {
        !required || (required && value != null &&
                (value !is String || !(value as? String).isNullOrEmpty()))
    }
```

Due to this change, some of the other FormElements were also needed to be changed. And to explain the customisation available, some changes would have to be made to the `base.md` doc under `element`.

If this looks okay, I can raise a PR for the same.

**Comment by TheJuki** [comment]
Go ahead with the PR.

**Comment by TheJuki** [comment]
I just released [6.2.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if validityCheck works for you.

**Comment by rdsarna** [comment]
Yes, validityCheck is working in the new version. Thank you.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.
