### ISSUE TITLE
Request: ProgressBarFormField

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#97]
Hi there,

I want to show a loading indicator within my form. But I have no idea how to add a view between some form fields. Something like that would be great:

```
formBuilder = form(context!!, recyclerView!!) {
button(1) {
    value = "Send"
    valueObservers.add { _, _ ->
        loadData()
    }
}
progress(2) {
    visible = false
}
}

fun loadData() {
        formBuilder.getFormElement<FormProgressElement>(2).visible = true
}
```

**Comment by TheJuki** [comment]
I just released [6.3.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if the new progress element works for you. Docs: https://thejuki.github.io/KFormMaster/element/progress/

**Comment by darkwood-studios** [comment]
I updated from 5.0.6 to 6.3.0 and got the following error:

ERROR: Failed to resolve: com.github.vivchar:RendererRecyclerViewAdapter:2.7.0-SNAPSHOT

**Comment by TheJuki** [comment]
https://github.com/TheJuki/KFormMaster#vivcharrendererrecyclerviewadapter-270

You need to add the sonatype snapshots repository to your root build.gradle.

repositories {
       maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

**Comment by darkwood-studios** [comment]
hmm, now i got this:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).

**Comment by TheJuki** [comment]
Are you using the Android Support library? You will need to be using AndroidX: https://developer.android.com/jetpack/androidx/

**Comment by darkwood-studios** [comment]
ah good tip. I will migrate to android x and test again

**Comment by darkwood-studios** [comment]
Works great. Thanks for the realization. :-)

I see one small layout problem. When I use a circle it's not centered within the view. It looks like its pulled to the right a bit. If I add the centerText param it's pulled even further to the right. 

Could you please check whats wrong there? The circle should be centered horizontal.

**Comment by TheJuki** [comment]
Use `displayTitle = true` for the best results.

**Comment by TheJuki** [comment]
I am closing this issue. If you have any issues feel free to reopen.

**Comment by darkwood-studios** [comment]
works great. thanks :-)
