### ISSUE TITLE
How to change background and padding of form

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#98]
Hi there,

I want to change the background color from white to something else and add some padding to the complete form. Any idea how to change the overall form layout?

best,
daniel

**Comment by TheJuki** [comment]
android:background="@color/colorFormMasterElementBackground"

Try overriding the colorFormMasterElementBackground color.

https://github.com/TheJuki/KFormMaster/blob/master/app/src/main/res/layout/activity_login_form.xml

You can checkout the login activity layout. It uses margins on the RecyclerView.

**Comment by darkwood-studios** [comment]
great. thx. :-)
